package eu.kanade.tachiyomi.animeextension.all.missav

import eu.kanade.tachiyomi.animesource.model.AnimeFilter
import eu.kanade.tachiyomi.animesource.model.AnimeFilterList

enum class MissAVGenre(
    val display: String,
    val match: String,
    val slug: String
) {
    UNCENSORED_LEAK("Uncensored Leak", "Uncensored Leak", "uncensored-leak"),
    HD("Hd", "Hd", "hd"),
    EXCLUSIVE("Exclusive", "Exclusive", "exclusive"),
    CREAMPIE("Creampie", "Creampie", "creampie"),
    BIG_BREASTS("Big Breasts", "Big Breasts", "big_breasts"),
    INDIVIDUAL("Individual", "Individual", "individual"),
    WIFE("Wife", "Wife", "wife"),
    MATURE_WOMAN("Mature Woman", "Mature Woman", "mature_woman"),
    ORDINARY_PERSON("Ordinary Person", "Ordinary Person", "ordinary_person"),
    PRETTY_GIRL("Pretty Girl", "Pretty Girl", "pretty_girl"),
    RIDE("Ride", "Ride", "ride"),
    ORAL_SEX("Oral Sex", "Oral Sex", "oral_sex"),
    ORGY("Orgy", "Orgy", "orgy"),
    SLIM_PIXELATED("Slim Pixelated", "Slim Pixelated", "slim_pixelated"),
    4_HOURS_OR_MORE("4 Hours Or More", "4 Hours Or More", "4_hours_or_more"),
    SLUT("Slut", "Slut", "slut"),
    COLLECTION("Collection", "Collection", "collection"),
    HIGH_SCHOOL_GIRL("High School Girl", "High School Girl", "high_school_girl"),
    SQUIRTING("Squirting", "Squirting", "squirting"),
    FETISH("Fetish", "Fetish", "fetish"),
    SELFIE("Selfie", "Selfie", "selfie"),
    TIT_JOB("Tit Job", "Tit Job", "tit_job"),
    PLANNING("Planning", "Planning", "planning"),
    INCEST("Incest", "Incest", "incest"),
    HIT_ON_GIRLS("Hit On Girls", "Hit On Girls", "hit_on_girls"),
    SNEAK_SHOTS("Sneak Shots", "Sneak Shots", "sneak_shots"),
    SLIM("Slim", "Slim", "slim"),
    BUKKAKE("Bukkake", "Bukkake", "bukkake"),
    BEAUTIFUL_BREASTS("Beautiful Breasts", "Beautiful Breasts", "beautiful_breasts"),
    MASTURBATE("Masturbate", "Masturbate", "masturbate"),
    MASTURBATION("Masturbation", "Masturbation", "masturbation"),
    RESTRAINT("Restraint", "Restraint", "restraint"),
    PROMISCUOUS("Promiscuous", "Promiscuous", "promiscuous"),
    LESBIAN("Lesbian", "Lesbian", "lesbian"),
    NTR("Ntr", "Ntr", "ntr"),
    SISTER("Sister", "Sister", "sister"),
    PLOT("Plot", "Plot", "plot"),
    COSPLAY("Cosplay", "Cosplay", "cosplay"),
    HUMILIATION("Humiliation", "Humiliation", "humiliation"),
    DOCUMENTARY("Documentary", "Documentary", "documentary"),
    HOT_GIRL("Hot Girl", "Hot Girl", "hot_girl"),
    OL("Ol", "Ol", "ol"),
    UNIFORM("Uniform", "Uniform", "uniform"),
    FINGERING("Fingering", "Fingering", "fingering"),
    VIBRATOR("Vibrator", "Vibrator", "vibrator"),
    ADULTERY("Adultery", "Adultery", "adultery"),
    CUNNILINGUS("Cunnilingus", "Cunnilingus", "cunnilingus"),
    DELUSION("Delusion", "Delusion", "delusion"),
    FEMALE_COLLEGE_STUDENT("Female College Student", "Female College Student", "female_college_student"),
    SM("Sm", "Sm", "sm"),
    SHAME("Shame", "Shame", "shame"),
    ANUS("Anus", "Anus", "anus"),
    UNIFORM("Uniform", "Uniform", "uniform"),
    PETITE("Petite", "Petite", "petite"),
    SHAVING("Shaving", "Shaving", "shaving"),
    SUBJECTIVE_PERSPECTIVE("Subjective Perspective", "Subjective Perspective", "subjective_perspective"),
    PROSTITUTE("Prostitute", "Prostitute", "prostitute"),
    VARIOUS_OCCUPATIONS("Various Occupations", "Various Occupations", "various_occupations"),
    MOTHER("Mother", "Mother", "mother"),
    VIBRATOR("Vibrator", "Vibrator", "vibrator"),
    TOY("Toy", "Toy", "toy"),
    PROMISCUITY("Promiscuity", "Promiscuity", "promiscuity"),
    OUTDOOR_EXPOSURE("Outdoor Exposure", "Outdoor Exposure", "outdoor_exposure"),
    BUTT_FETISH("Butt Fetish", "Butt Fetish", "butt_fetish"),
    PANTYHOSE("Pantyhose", "Pantyhose", "pantyhose"),
    DEBUT("Debut", "Debut", "debut"),
    URINATE("Urinate", "Urinate", "urinate"),
    DIRTY_TALK("Dirty Talk", "Dirty Talk", "dirty_talk"),
    MASSAGE("Massage", "Massage", "massage"),
    UNDERWEAR("Underwear", "Underwear", "underwear"),
    BIG_ASS("Big Ass", "Big Ass", "big_ass"),
    FORCED_BLOWJOB("Forced Blowjob", "Forced Blowjob", "forced_blowjob"),
    SAILOR_SUIT("Sailor Suit", "Sailor Suit", "sailor_suit"),
    SWIMSUIT("Swimsuit", "Swimsuit", "swimsuit"),
    DELIVERY_ONLY("Delivery Only", "Delivery Only", "delivery_only"),
    FEMALE_TEACHER("Female Teacher", "Female Teacher", "female_teacher"),
    KIMONO("Kimono", "Kimono", "kimono"),
    SWALLOW_SPERM("Swallow Sperm", "Swallow Sperm", "swallow_sperm"),
    69("69", "69", "69"),
    SMALL_BREASTS("Small Breasts", "Small Breasts", "small_breasts"),
    ELDER_SISTER("Elder Sister", "Elder Sister", "elder_sister"),
    YOUNG_WIFE("Young Wife", "Young Wife", "young_wife"),
    NURSE("Nurse", "Nurse", "nurse"),
    MASSAGE_OIL("Massage Oil", "Massage Oil", "massage_oil"),
    GROUP_BUKKAKE("Group Bukkake", "Group Bukkake", "group_bukkake"),
    TIED_UP("Tied Up", "Tied Up", "tied_up"),
    FAT_GIRL("Fat Girl", "Fat Girl", "fat_girl"),
    REJUVENATION_MASSAGE("Rejuvenation Massage", "Rejuvenation Massage", "rejuvenation_massage"),
    SHORT_SKIRT("Short Skirt", "Short Skirt", "short_skirt"),
    ULTRA_SLIM_PIXELATED("Ultra Slim Pixelated", "Ultra Slim Pixelated", "ultra_slim_pixelated"),
    CONTRIBUTION("Contribution", "Contribution", "contribution"),
    NICE_ASS("Nice Ass", "Nice Ass", "nice_ass"),
    FOOT_FETISH("Foot Fetish", "Foot Fetish", "foot_fetish"),
    FULL_HD_FHD("Full Hd (Fhd)", "Full Hd (Fhd)", "full_hd_fhd"),
    GLASSES_GIRL("Glasses Girl", "Glasses Girl", "glasses_girl"),
    KISS("Kiss", "Kiss", "kiss"),
    4K("4K", "4K", "4k"),
    CLOSE_UP("Close Up", "Close Up", "close_up"),
    BIG_BREASTS("Big Breasts", "Big Breasts", "big_breasts"),
    TIED_UP("Tied Up", "Tied Up", "tied_up"),
    BIG_BREAST_FETISH("Big Breast Fetish", "Big Breast Fetish", "big_breast_fetish"),
    SWIMSUIT("Swimsuit", "Swimsuit", "swimsuit"),
    SPORTSWEAR("Sportswear", "Sportswear", "sportswear"),
    VIRGIN("Virgin", "Virgin", "virgin"),
    VIBRATING_EGG("Vibrating Egg", "Vibrating Egg", "vibrating_egg"),
    APHRODISIAC("Aphrodisiac", "Aphrodisiac", "aphrodisiac"),
    LESBIAN_KISS("Lesbian Kiss", "Lesbian Kiss", "lesbian_kiss"),
    MINI_SKIRT("Mini Skirt", "Mini Skirt", "mini_skirt"),
    WHITE_SKIN("White Skin", "White Skin", "white_skin"),
    M_MALE("M Male", "M Male", "m_male"),
    COUPLE("Couple", "Couple", "couple"),
    HOT_SPRING("Hot Spring", "Hot Spring", "hot_spring"),
    MAID("Maid", "Maid", "maid"),
    FACE_RIDE("Face Ride", "Face Ride", "face_ride"),
    IMPRISONMENT("Imprisonment", "Imprisonment", "imprisonment"),
    FOOTJOB("Footjob", "Footjob", "footjob"),
    FIGHTING("Fighting", "Fighting", "fighting"),
    TALL_LADY("Tall Lady", "Tall Lady", "tall_lady"),
    FEMALE_WARRIOR("Female Warrior", "Female Warrior", "female_warrior"),
    ARTIST("Artist", "Artist", "artist"),
    SCIENCE_FICTION("Science Fiction", "Science Fiction", "science_fiction"),
    MISCHIEF("Mischief", "Mischief", "mischief"),
    ACTRESS_COLLECTION("Actress Collection", "Actress Collection", "actress_collection"),
    MARRIED_WOMAN("Married Woman", "Married Woman", "married_woman"),
    SWEATING("Sweating", "Sweating", "sweating"),
    BLACK_MALE_ACTOR("Black Male Actor", "Black Male Actor", "black_male_actor"),
    STEPMOTHER("Stepmother", "Stepmother", "stepmother"),
    PETITE("Petite", "Petite", "petite"),
    BEAUTIFUL_LEGS("Beautiful Legs", "Beautiful Legs", "beautiful_legs"),
    PRIVATE_TEACHER("Private Teacher", "Private Teacher", "private_teacher"),
    BIG_PENNIS("Big Pennis", "Big Pennis", "big_pennis"),
    SUPER_BREASTS("Super Breasts", "Super Breasts", "super_breasts"),
    ADVERTISING_IDOL("Advertising Idol", "Advertising Idol", "advertising_idol"),
    TORTURE("Torture", "Torture", "torture"),
    EMMANUEL("Emmanuel", "Emmanuel", "emmanuel"),
    ANAL_SEX("Anal Sex", "Anal Sex", "anal_sex"),
    BLACK_HAIR("Black Hair", "Black Hair", "black_hair"),
    BEAUTIFUL_BREASTS("Beautiful Breasts", "Beautiful Breasts", "beautiful_breasts"),
    EROTIC_PHOTO("Erotic Photo", "Erotic Photo", "erotic_photo"),
    WIDOW("Widow", "Widow", "widow"),
    GYM_SUIT("Gym Suit", "Gym Suit", "gym_suit"),
    CRUEL("Cruel", "Cruel", "cruel"),
    SEXY("Sexy", "Sexy", "sexy"),
    CAR_SEX("Car Sex", "Car Sex", "car_sex"),
    MULTIPLE_STORIES("Multiple Stories", "Multiple Stories", "multiple_stories"),
    CAMPUS_STORY("Campus Story", "Campus Story", "campus_story"),
    3P_4P("3P, 4P", "3P, 4P", "3p_4p"),
    TRANSGENDER("Transgender", "Transgender", "transgender"),
    SLIM("Slim", "Slim", "slim"),
    FEMALE_DOCTOR("Female Doctor", "Female Doctor", "female_doctor"),
    IN_LOVE("In Love", "In Love", "in_love"),
    FIGHTER("Fighter", "Fighter", "fighter"),
    FANTASY("Fantasy", "Fantasy", "fantasy"),
    PURE("Pure", "Pure", "pure"),
    VIRGIN("Virgin", "Virgin", "virgin"),
    INSTANT_SEX("Instant Sex", "Instant Sex", "instant_sex"),
    MISSY("Missy", "Missy", "missy"),
    ENEMA("Enema", "Enema", "enema"),
    DANCE("Dance", "Dance", "dance"),
    FEMININE("Feminine", "Feminine", "feminine"),
    BEST_OMNIBUS("Best, Omnibus", "Best, Omnibus", "best_omnibus"),
    WHITES("Whites", "Whites", "whites"),
    FLIGHT_ATTENDANT("Flight Attendant", "Flight Attendant", "flight_attendant"),
    HAREM("Harem", "Harem", "harem"),
    FOREIGN_ACTRESS("Foreign Actress", "Foreign Actress", "foreign_actress"),
    PHYSICAL_EDUCATION("Physical Education", "Physical Education", "physical_education"),
    BRONZE("Bronze", "Bronze", "bronze"),
    FEMALE_INVESTIGATOR("Female Investigator", "Female Investigator", "female_investigator"),
    TRANSSEXUALS("Transsexuals", "Transsexuals", "transsexuals"),
    MODEL("Model", "Model", "model"),
    BABY_FACE("Baby Face", "Baby Face", "baby_face"),
    DOGGY_STYLE("Doggy Style", "Doggy Style", "doggy_style"),
    SHAVING("Shaving", "Shaving", "shaving"),
    BITCH("Bitch", "Bitch", "bitch"),
    BLOOMERS("Bloomers", "Bloomers", "bloomers"),
    ONE_PIECE_DRESS("One Piece Dress", "One Piece Dress", "one_piece_dress"),
    KNEE_SOCKS("Knee Socks", "Knee Socks", "knee_socks"),
    THANKS_OFFERING("Thanks Offering", "Thanks Offering", "thanks_offering"),
    CUTE_LITTLE_BOY("Cute Little Boy", "Cute Little Boy", "cute_little_boy"),
    DELIVERY_ONLY_AMATEUR("Delivery-Only Amateur", "Delivery-Only Amateur", "delivery_only_amateur"),
    OTHER("Other", "Other", "other"),
    BUBBLE_BATH("Bubble Bath", "Bubble Bath", "bubble_bath"),
    TICKLE("Tickle", "Tickle", "tickle"),
    HIGH_SCHOOL_GIRL("High School Girl", "High School Girl", "high_school_girl"),
    SISTER("Sister", "Sister", "sister"),
    EXTREME_ORGASM("Extreme Orgasm", "Extreme Orgasm", "extreme_orgasm"),
    BREAST_MILK("Breast Milk", "Breast Milk", "breast_milk"),
    M_FEMALE("M Female", "M Female", "m_female"),
    PREGNANT_WOMAN("Pregnant Woman", "Pregnant Woman", "pregnant_woman"),
    INDIE("Indie", "Indie", "indie"),
    HOMOSEXUAL("Homosexual", "Homosexual", "homosexual"),
    VR("Vr", "Vr", "vr"),
    DRINK_URINE("Drink Urine", "Drink Urine", "drink_urine"),
    RACING_GIRL("Racing Girl", "Racing Girl", "racing_girl"),
    FEMDOM_SLAVE("Femdom Slave", "Femdom Slave", "femdom_slave"),
    HEAVEN_TV("Heaven Tv", "Heaven Tv", "heaven_tv"),
    SECRETARY("Secretary", "Secretary", "secretary"),
    INSULT("Insult", "Insult", "insult"),
    HOT_GIRL("Hot Girl", "Hot Girl", "hot_girl"),
    SMALL_BREASTS("Small Breasts", "Small Breasts", "small_breasts"),
    RAPE("Rape", "Rape", "rape"),
    THIRTY("Thirty", "Thirty", "thirty"),
    LOLITA("Lolita", "Lolita", "lolita"),
    FEMALE_BOSS("Female Boss", "Female Boss", "female_boss"),
    FOREIGN_OBJECT_PENETRATION("Foreign Object Penetration", "Foreign Object Penetration", "foreign_object_penetration"),
    HIT_ON_BOYS("Hit On Boys", "Hit On Boys", "hit_on_boys"),
    STOOL("Stool", "Stool", "stool"),
    HYSTEROSCOPE("Hysteroscope", "Hysteroscope", "hysteroscope"),
    YOUNG_WIFE("Young Wife", "Young Wife", "young_wife"),
    DEFECATION("Defecation", "Defecation", "defecation"),
    GANG_RAPE("Gang Rape", "Gang Rape", "gang_rape"),
    ANCHORWOMAN("Anchorwoman", "Anchorwoman", "anchorwoman"),
    HIGH_QUALITY_VR("High Quality Vr", "High Quality Vr", "high_quality_vr"),
    SIMILAR("Similar", "Similar", "similar"),
    TRANSSEXUALS("Transsexuals", "Transsexuals", "transsexuals"),
    CATWOMAN("Catwoman", "Catwoman", "catwoman"),
    BATHTUB("Bathtub", "Bathtub", "bathtub"),
    DILDO("Dildo", "Dildo", "dildo"),
    LIMITED_TIME("Limited Time", "Limited Time", "limited_time"),
    FIST("Fist", "Fist", "fist"),
    DATING("Dating", "Dating", "dating"),
    CUCKOLD("Cuckold", "Cuckold", "cuckold"),
    ORIGINAL("Original", "Original", "original"),
    LECTURER("Lecturer", "Lecturer", "lecturer"),
    ESTHETIC_MASSAGE("Esthetic Massage", "Esthetic Massage", "esthetic_massage"),
    CHILDHOOD("Childhood", "Childhood", "childhood"),
    UTERUS("Uterus", "Uterus", "uterus"),
    PREGNANT("Pregnant", "Pregnant", "pregnant"),
    ENTERTAINER("Entertainer", "Entertainer", "entertainer"),
    LONG_HAIR("Long Hair", "Long Hair", "long_hair"),
    PETITE("Petite", "Petite", "petite"),
    FIRST_SHOT("First Shot", "First Shot", "first_shot"),
    MUSCLE("Muscle", "Muscle", "muscle"),
    OUTDOORS("Outdoors", "Outdoors", "outdoors"),
    NAKED_APRON("Naked Apron", "Naked Apron", "naked_apron"),
    MALE_SQUIRTING("Male Squirting", "Male Squirting", "male_squirting"),
    HOTEL_OWNER("Hotel Owner", "Hotel Owner", "hotel_owner"),
    MOLESTER("Molester", "Molester", "molester"),
    ARTIST("Artist", "Artist", "artist"),
    BUNNY_GIRL("Bunny Girl", "Bunny Girl", "bunny_girl"),
    TRAVEL("Travel", "Travel", "travel"),
    RACING_GIRL("Racing Girl", "Racing Girl", "racing_girl"),
    ASIAN_ACTRESS("Asian Actress", "Asian Actress", "asian_actress"),
    TENTACLE("Tentacle", "Tentacle", "tentacle"),
    PROUD_PUSSY("Proud Pussy", "Proud Pussy", "proud_pussy"),
    SUBORDINATE_OR_COLLEAGUE("Subordinate Or Colleague", "Subordinate Or Colleague", "subordinate_or_colleague"),
    WITH_BONUS_VIDEO_ONLY_FOR_MGS("With Bonus Video Only For Mgs", "With Bonus Video Only For Mgs", "with_bonus_video_only_for_mgs"),
    BUSINESS_CLOTHING("Business Clothing", "Business Clothing", "business_clothing"),
    PREMATURE_EJACULATION("Premature Ejaculation", "Premature Ejaculation", "premature_ejaculation"),
    FRIEND("Friend", "Friend", "friend"),
    SHAME_AND_HUMILIATION("Shame And Humiliation", "Shame And Humiliation", "shame_and_humiliation"),
    BIG_BREASTS("Big Breasts", "Big Breasts", "big_breasts"),
    SHORT_HAIR("Short Hair", "Short Hair", "short_hair"),
    DILDO("Dildo", "Dildo", "dildo"),
    LIMITED_TIME("Limited Time", "Limited Time", "limited_time"),
    FIST("Fist", "Fist", "fist"),
    DATING("Dating", "Dating", "dating"),
    CUCKOLD("Cuckold", "Cuckold", "cuckold"),
    ORIGINAL("Original", "Original", "original"),
    LECTURER("Lecturer", "Lecturer", "lecturer"),
    ESTHETIC_MASSAGE("Esthetic Massage", "Esthetic Massage", "esthetic_massage"),
    CHILDHOOD("Childhood", "Childhood", "childhood"),
    UTERUS("Uterus", "Uterus", "uterus"),
    PREGNANT("Pregnant", "Pregnant", "pregnant"),
    ENTERTAINER("Entertainer", "Entertainer", "entertainer"),
    LONG_HAIR("Long Hair", "Long Hair", "long_hair"),
    PETITE("Petite", "Petite", "petite"),
    FIRST_SHOT("First Shot", "First Shot", "first_shot"),
    MUSCLE("Muscle", "Muscle", "muscle"),
    OUTDOORS("Outdoors", "Outdoors", "outdoors"),
    NAKED_APRON("Naked Apron", "Naked Apron", "naked_apron"),
    MALE_SQUIRTING("Male Squirting", "Male Squirting", "male_squirting"),
    HOTEL_OWNER("Hotel Owner", "Hotel Owner", "hotel_owner"),
    MOLESTER("Molester", "Molester", "molester"),
    ARTIST("Artist", "Artist", "artist"),
    BUNNY_GIRL("Bunny Girl", "Bunny Girl", "bunny_girl"),
    TRAVEL("Travel", "Travel", "travel"),
    RACING_GIRL("Racing Girl", "Racing Girl", "racing_girl"),
    ASIAN_ACTRESS("Asian Actress", "Asian Actress", "asian_actress"),
    TENTACLE("Tentacle", "Tentacle", "tentacle"),
    PROUD_PUSSY("Proud Pussy", "Proud Pussy", "proud_pussy"),
    SUBORDINATE_OR_COLLEAGUE("Subordinate Or Colleague", "Subordinate Or Colleague", "subordinate_or_colleague"),
    WITH_BONUS_VIDEO_ONLY_FOR_MGS("With Bonus Video Only For Mgs", "With Bonus Video Only For Mgs", "with_bonus_video_only_for_mgs"),
    BUSINESS_CLOTHING("Business Clothing", "Business Clothing", "business_clothing"),
    PREMATURE_EJACULATION("Premature Ejaculation", "Premature Ejaculation", "premature_ejaculation"),
    FRIEND("Friend", "Friend", "friend"),
    SHAME_AND_HUMILIATION("Shame And Humiliation", "Shame And Humiliation", "shame_and_humiliation"),
    BIG_BREASTS("Big Breasts", "Big Breasts", "big_breasts"),
    SHORT_HAIR("Short Hair", "Short Hair", "short_hair"),
    WAITRESS("Waitress", "Waitress", "waitress"),
    CLINIC("Clinic", "Clinic", "clinic"),
    EXPOSURE("Exposure", "Exposure", "exposure"),
    KIMONO_YUKATA("Kimono / Yukata", "Kimono / Yukata", "kimono_yukata"),
    LEWD_NASTY_LADY("Lewd Nasty Lady", "Lewd Nasty Lady", "lewd_nasty_lady"),
    BUBBLE_SOCKS("Bubble Socks", "Bubble Socks", "bubble_socks"),
    FANTASY("Fantasy", "Fantasy", "fantasy"),
    IDOL("Idol", "Idol", "idol"),
    TIME_STOPS("Time Stops", "Time Stops", "time_stops");
    
    companion object {
        fun fromDisplay(display: String): MissAVGenre? {
            return entries.find { it.display == display }
        }
    }
}

class GenreList : AnimeFilter.Select<String>(
    "Genre (Single - Fast)",
    arrayOf("") + MissAVGenre.entries.map { it.display }
)

class TriGenre(val genre: MissAVGenre) : AnimeFilter.TriState(genre.display)

class MultiGenreFilter : AnimeFilter.Group<AnimeFilter.TriState>(
    "Genres (Multi - Slow)",
    MissAVGenre.entries.map { TriGenre(it) }
)

data class FilterParams(
    val include: List<MissAVGenre>,
    val exclude: List<MissAVGenre>
)

fun extractParams(filters: AnimeFilterList): FilterParams {
    val include = mutableListOf<MissAVGenre>()
    val exclude = mutableListOf<MissAVGenre>()

    filters.filterIsInstance<MultiGenreFilter>().firstOrNull()?.state?.forEach {
        val g = (it as TriGenre).genre
        when (it.state) {
            AnimeFilter.TriState.STATE_INCLUDE -> include.add(g)
            AnimeFilter.TriState.STATE_EXCLUDE -> exclude.add(g)
            else -> {}
        }
    }
    
    return FilterParams(include, exclude)
}

fun getFilters(): AnimeFilterList {
    return AnimeFilterList(
        GenreList(),
        AnimeFilter.Separator(),
        MultiGenreFilter(),
        AnimeFilter.Header("📌 FILTER GUIDE"),
        AnimeFilter.Header("Single Genre: Fast server-side filtering"),
        AnimeFilter.Header("Multi-Genre: Client-side filtering (slow)"),
        AnimeFilter.Header("✓ = Include | ✗ = Exclude | Empty = Ignore"),
        AnimeFilter.Header("Multi-genre uses first tag as base search"),
    )
}
