package eu.kanade.tachiyomi.animeextension.all.missav

import eu.kanade.tachiyomi.animesource.model.AnimeFilter
import eu.kanade.tachiyomi.animesource.model.AnimeFilterList

// Simple data class for genre
data class Genre(val display: String, val slug: String)

class SingleGenreFilter : AnimeFilter.Select<String>(
    "Genre (Single - Fast)",
    arrayOf(
        "",
        "Uncensored Leak",
        "HD",
        "Exclusive",
        "Creampie",
        "Big Breasts",
        "Individual",
        "Wife",
        "Mature Woman",
        "Ordinary Person",
        "Pretty Girl",
        "Ride",
        "Oral Sex",
        "Orgy",
        "Slim Pixelated",
        "4 Hours Or More",
        "Slut",
        "Collection",
        "High School Girl",
        "Squirting",
        "Fetish",
        "Selfie",
        "Tit Job",
        "Planning",
        "Incest",
        "Hit On Girls",
        "Sneak Shots",
        "Slim",
        "Bukkake",
        "Beautiful Breasts",
        "Masturbate",
        "Masturbation",
        "Restraint",
        "Promiscuous",
        "Lesbian",
        "Ntr",
        "Sister",
        "Plot",
        "Cosplay",
        "Humiliation",
        "Documentary",
        "Hot Girl",
        "Ol",
        "Uniform",
        "Fingering",
        "Vibrator",
        "Adultery",
        "Cunnilingus",
        "Delusion",
        "Female College Student",
        "Sm",
        "Shame",
        "Anus",
        "Uniform",
        "Petite",
        "Shaving",
        "Subjective Perspective",
        "Prostitute",
        "Various Occupations",
        "Mother",
        "Vibrator",
        "Toy",
        "Promiscuity",
        "Outdoor Exposure",
        "Butt Fetish",
        "Pantyhose",
        "Debut",
        "Urinate",
        "Dirty Talk",
        "Massage",
        "Underwear",
        "Big Ass",
        "Forced Blowjob",
        "Sailor Suit",
        "Swimsuit",
        "Delivery Only",
        "Female Teacher",
        "Kimono",
        "Swallow Sperm",
        "69",
        "Small Breasts",
        "Elder Sister",
        "Young Wife",
        "Nurse",
        "Massage Oil",
        "Group Bukkake",
        "Tied Up",
        "Fat Girl",
        "Rejuvenation Massage",
        "Short Skirt",
        "Ultra Slim Pixelated",
        "Contribution",
        "Nice Ass",
        "Foot Fetish",
        "Full Hd (Fhd)",
        "Glasses Girl",
        "Kiss",
        "4K",
        "Close Up",
        "Big Breasts",
        "Tied Up",
        "Big Breast Fetish",
        "Swimsuit",
        "Sportswear",
        "Virgin",
        "Vibrating Egg",
        "Aphrodisiac",
        "Lesbian Kiss",
        "Mini Skirt",
        "White Skin",
        "M Male",
        "Couple",
        "Hot Spring",
        "Maid",
        "Face Ride",
        "Imprisonment",
        "Footjob",
        "Fighting",
        "Tall Lady",
        "Female Warrior",
        "Artist",
        "Science Fiction",
        "Mischief",
        "Actress Collection",
        "Married Woman",
        "Sweating",
        "Black Male Actor",
        "Stepmother",
        "Petite",
        "Beautiful Legs",
        "Private Teacher",
        "Big Pennis",
        "Super Breasts",
        "Advertising Idol",
        "Torture",
        "Emmanuel",
        "Anal Sex",
        "Black Hair",
        "Beautiful Breasts",
        "Erotic Photo",
        "Widow",
        "Gym Suit",
        "Cruel",
        "Sexy",
        "Car Sex",
        "Multiple Stories",
        "Campus Story",
        "3P, 4P",
        "Transgender",
        "Slim",
        "Female Doctor",
        "In Love",
        "Fighter",
        "Fantasy",
        "Pure",
        "Virgin",
        "Instant Sex",
        "Missy",
        "Enema",
        "Dance",
        "Feminine",
        "Best, Omnibus",
        "Whites",
        "Flight Attendant",
        "Harem",
        "Foreign Actress",
        "Physical Education",
        "Bronze",
        "Female Investigator",
        "Transsexuals",
        "Model",
        "Baby Face",
        "Doggy Style",
        "Shaving",
        "Bitch",
        "Bloomers",
        "One Piece Dress",
        "Knee Socks",
        "Thanks Offering",
        "Cute Little Boy",
        "Delivery-Only Amateur",
        "Other",
        "Bubble Bath",
        "Tickle",
        "High School Girl",
        "Sister",
        "Extreme Orgasm",
        "Breast Milk",
        "M Female",
        "Pregnant Woman",
        "Indie",
        "Homosexual",
        "Vr",
        "Drink Urine",
        "Racing Girl",
        "Femdom Slave",
        "Heaven Tv",
        "Secretary",
        "Insult",
        "Hot Girl",
        "Small Breasts",
        "Rape",
        "Thirty",
        "Lolita",
        "Female Boss",
        "Foreign Object Penetration",
        "Hit On Boys",
        "Stool",
        "Hysteroscope",
        "Young Wife",
        "Defecation",
        "Gang Rape",
        "Anchorwoman",
        "High Quality Vr",
        "Similar",
        "Transsexuals",
        "Catwoman",
        "Bathtub",
        "Dildo",
        "Limited Time",
        "Fist",
        "Dating",
        "Cuckold",
        "Original",
        "Lecturer",
        "Esthetic Massage",
        "Childhood",
        "Uterus",
        "Pregnant",
        "Entertainer",
        "Long Hair",
        "Petite",
        "First Shot",
        "Muscle",
        "Outdoors",
        "Naked Apron",
        "Male Squirting",
        "Hotel Owner",
        "Molester",
        "Artist",
        "Bunny Girl",
        "Travel",
        "Racing Girl",
        "Asian Actress",
        "Tentacle",
        "Proud Pussy",
        "Subordinate Or Colleague",
        "With Bonus Video Only For Mgs",
        "Business Clothing",
        "Premature Ejaculation",
        "Friend",
        "Shame And Humiliation",
        "Big Breasts",
        "Short Hair",
        "Dildo",
        "Limited Time",
        "Fist",
        "Dating",
        "Cuckold",
        "Original",
        "Lecturer",
        "Esthetic Massage",
        "Childhood",
        "Uterus",
        "Pregnant",
        "Entertainer",
        "Long Hair",
        "Petite",
        "First Shot",
        "Muscle",
        "Outdoors",
        "Naked Apron",
        "Male Squirting",
        "Hotel Owner",
        "Molester",
        "Artist",
        "Bunny Girl",
        "Travel",
        "Racing Girl",
        "Asian Actress",
        "Tentacle",
        "Proud Pussy",
        "Subordinate Or Colleague",
        "With Bonus Video Only For Mgs",
        "Business Clothing",
        "Premature Ejaculation",
        "Friend",
        "Shame And Humiliation",
        "Big Breasts",
        "Short Hair",
        "Waitress",
        "Clinic",
        "Exposure",
        "Kimono / Yukata",
        "Lewd Nasty Lady",
        "Bubble Socks",
        "Fantasy",
        "Idol",
        "Time Stops",
    ),
) {
    companion object {
        val GENRES = listOf(
            Pair("", ""),
            Pair("Uncensored Leak", "en/uncensored-leak"),
            Pair("HD", "en/genres/hd"),
            Pair("Exclusive", "en/genres/exclusive"),
            Pair("Creampie", "en/genres/Creampie"),
            Pair("Big Breasts", "en/genres/Big%20Breasts"),
            Pair("Individual", "en/genres/Individual"),
            Pair("Wife", "en/genres/Wife"),
            Pair("Mature Woman", "en/genres/Mature%20Woman"),
            Pair("Ordinary Person", "en/genres/Ordinary%20Person"),
            Pair("Pretty Girl", "en/genres/Pretty%20Girl"),
            Pair("Ride", "en/genres/Ride"),
            Pair("Oral Sex", "en/genres/Oral%20Sex"),
            Pair("Orgy", "en/genres/Orgy"),
            Pair("Slim Pixelated", "en/genres/Slim%20Pixelated"),
            Pair("4 Hours Or More", "en/genres/4%20Hours%20Or%20More"),
            Pair("Slut", "en/genres/Slut"),
            Pair("Collection", "en/genres/Collection"),
            Pair("High School Girl", "en/genres/High%20School%20Girl"),
            Pair("Squirting", "en/genres/Squirting"),
            Pair("Fetish", "en/genres/Fetish"),
            Pair("Selfie", "en/genres/Selfie"),
            Pair("Tit Job", "en/genres/Tit%20Job"),
            Pair("Planning", "en/genres/Planning"),
            Pair("Incest", "en/genres/Incest"),
            Pair("Hit On Girls", "en/genres/Hit%20On%20Girls"),
            Pair("Sneak Shots", "en/genres/Sneak%20Shots"),
            Pair("Slim", "en/genres/Slim"),
            Pair("Bukkake", "en/genres/Bukkake"),
            Pair("Beautiful Breasts", "en/genres/Beautiful%20Breasts"),
            Pair("Masturbate", "en/genres/Masturbate"),
            Pair("Masturbation", "en/genres/Masturbation"),
            Pair("Restraint", "en/genres/Restraint"),
            Pair("Promiscuous", "en/genres/Promiscuous"),
            Pair("Lesbian", "en/genres/Lesbian"),
            Pair("Ntr", "en/genres/Ntr"),
            Pair("Sister", "en/genres/Sister"),
            Pair("Plot", "en/genres/Plot"),
            Pair("Cosplay", "en/genres/Cosplay"),
            Pair("Humiliation", "en/genres/Humiliation"),
            Pair("Documentary", "en/genres/Documentary"),
            Pair("Hot Girl", "en/genres/Hot%20Girl"),
            Pair("Ol", "en/genres/Ol"),
            Pair("Uniform", "en/genres/Uniform"),
            Pair("Fingering", "en/genres/Fingering"),
            Pair("Vibrator", "en/genres/Vibrator"),
            Pair("Adultery", "en/genres/Adultery"),
            Pair("Cunnilingus", "en/genres/Cunnilingus"),
            Pair("Delusion", "en/genres/Delusion"),
            Pair("Female College Student", "en/genres/Female%20College%20Student"),
            Pair("Sm", "en/genres/Sm"),
            Pair("Shame", "en/genres/Shame"),
            Pair("Anus", "en/genres/Anus"),
            Pair("Uniform", "en/genres/Uniform"),
            Pair("Petite", "en/genres/Petite"),
            Pair("Shaving", "en/genres/Shaving"),
            Pair("Subjective Perspective", "en/genres/Subjective%20Perspective"),
            Pair("Prostitute", "en/genres/Prostitute"),
            Pair("Various Occupations", "en/genres/Various%20Occupations"),
            Pair("Mother", "en/genres/Mother"),
            Pair("Vibrator", "en/genres/Vibrator"),
            Pair("Toy", "en/genres/Toy"),
            Pair("Promiscuity", "en/genres/Promiscuity"),
            Pair("Outdoor Exposure", "en/genres/Outdoor%20Exposure"),
            Pair("Butt Fetish", "en/genres/Butt%20Fetish"),
            Pair("Pantyhose", "en/genres/Pantyhose"),
            Pair("Debut", "en/genres/Debut"),
            Pair("Urinate", "en/genres/Urinate"),
            Pair("Dirty Talk", "en/genres/Dirty%20Talk"),
            Pair("Massage", "en/genres/Massage"),
            Pair("Underwear", "en/genres/Underwear"),
            Pair("Big Ass", "en/genres/Big%20Ass"),
            Pair("Forced Blowjob", "en/genres/Forced%20Blowjob"),
            Pair("Sailor Suit", "en/genres/Sailor%20Suit"),
            Pair("Swimsuit", "en/genres/Swimsuit"),
            Pair("Delivery Only", "en/genres/Delivery%20Only"),
            Pair("Female Teacher", "en/genres/Female%20Teacher"),
            Pair("Kimono", "en/genres/Kimono"),
            Pair("Swallow Sperm", "en/genres/Swallow%20Sperm"),
            Pair("69", "en/genres/69"),
            Pair("Small Breasts", "en/genres/Small%20Breasts"),
            Pair("Elder Sister", "en/genres/Elder%20Sister"),
            Pair("Young Wife", "en/genres/Young%20Wife"),
            Pair("Nurse", "en/genres/Nurse"),
            Pair("Massage Oil", "en/genres/Massage%20Oil"),
            Pair("Group Bukkake", "en/genres/Group%20Bukkake"),
            Pair("Tied Up", "en/genres/Tied%20Up"),
            Pair("Fat Girl", "en/genres/Fat%20Girl"),
            Pair("Rejuvenation Massage", "en/genres/Rejuvenation%20Massage"),
            Pair("Short Skirt", "en/genres/Short%20Skirt"),
            Pair("Ultra Slim Pixelated", "en/genres/Ultra%20Slim%20Pixelated"),
            Pair("Contribution", "en/genres/Contribution"),
            Pair("Nice Ass", "en/genres/Nice%20Ass"),
            Pair("Foot Fetish", "en/genres/Foot%20Fetish"),
            Pair("Full Hd (Fhd)", "en/genres/Full%20Hd%20%28Fhd%29"),
            Pair("Glasses Girl", "en/genres/Glasses%20Girl"),
            Pair("Kiss", "en/genres/Kiss"),
            Pair("4K", "en/genres/4K"),
            Pair("Close Up", "en/genres/Close%20Up"),
            Pair("Big Breasts", "en/genres/Big%20Breasts"),
            Pair("Tied Up", "en/genres/Tied%20Up"),
            Pair("Big Breast Fetish", "en/genres/Big%20Breast%20Fetish"),
            Pair("Swimsuit", "en/genres/Swimsuit"),
            Pair("Sportswear", "en/genres/Sportswear"),
            Pair("Virgin", "en/genres/Virgin"),
            Pair("Vibrating Egg", "en/genres/Vibrating%20Egg"),
            Pair("Aphrodisiac", "en/genres/Aphrodisiac"),
            Pair("Lesbian Kiss", "en/genres/Lesbian%20Kiss"),
            Pair("Mini Skirt", "en/genres/Mini%20Skirt"),
            Pair("White Skin", "en/genres/White%20Skin"),
            Pair("M Male", "en/genres/M%20Male"),
            Pair("Couple", "en/genres/Couple"),
            Pair("Hot Spring", "en/genres/Hot%20Spring"),
            Pair("Maid", "en/genres/Maid"),
            Pair("Face Ride", "en/genres/Face%20Ride"),
            Pair("Imprisonment", "en/genres/Imprisonment"),
            Pair("Footjob", "en/genres/Footjob"),
            Pair("Fighting", "en/genres/Fighting"),
            Pair("Tall Lady", "en/genres/Tall%20Lady"),
            Pair("Female Warrior", "en/genres/Female%20Warrior"),
            Pair("Artist", "en/genres/Artist"),
            Pair("Science Fiction", "en/genres/Science%20Fiction"),
            Pair("Mischief", "en/genres/Mischief"),
            Pair("Actress Collection", "en/genres/Actress%20Collection"),
            Pair("Married Woman", "en/genres/Married%20Woman"),
            Pair("Sweating", "en/genres/Sweating"),
            Pair("Black Male Actor", "en/genres/Black%20Male%20Actor"),
            Pair("Stepmother", "en/genres/Stepmother"),
            Pair("Petite", "en/genres/Petite"),
            Pair("Beautiful Legs", "en/genres/Beautiful%20Legs"),
            Pair("Private Teacher", "en/genres/Private%20Teacher"),
            Pair("Big Pennis", "en/genres/Big%20Pennis"),
            Pair("Super Breasts", "en/genres/Super%20Breasts"),
            Pair("Advertising Idol", "en/genres/Advertising%20Idol"),
            Pair("Torture", "en/genres/Torture"),
            Pair("Emmanuel", "en/genres/Emmanuel"),
            Pair("Anal Sex", "en/genres/Anal%20Sex"),
            Pair("Black Hair", "en/genres/Black%20Hair"),
            Pair("Beautiful Breasts", "en/genres/Beautiful%20Breasts"),
            Pair("Erotic Photo", "en/genres/Erotic%20Photo"),
            Pair("Widow", "en/genres/Widow"),
            Pair("Gym Suit", "en/genres/Gym%20Suit"),
            Pair("Cruel", "en/genres/Cruel"),
            Pair("Sexy", "en/genres/Sexy"),
            Pair("Car Sex", "en/genres/Car%20Sex"),
            Pair("Multiple Stories", "en/genres/Multiple%20Stories"),
            Pair("Campus Story", "en/genres/Campus%20Story"),
            Pair("3P, 4P", "en/genres/3P,%204P"),
            Pair("Transgender", "en/genres/Transgender"),
            Pair("Slim", "en/genres/Slim"),
            Pair("Female Doctor", "en/genres/Female%20Doctor"),
            Pair("In Love", "en/genres/In%20Love"),
            Pair("Fighter", "en/genres/Fighter"),
            Pair("Fantasy", "en/genres/Fantasy"),
            Pair("Pure", "en/genres/Pure"),
            Pair("Virgin", "en/genres/Virgin"),
            Pair("Instant Sex", "en/genres/Instant%20Sex"),
            Pair("Missy", "en/genres/Missy"),
            Pair("Enema", "en/genresenema"),
            Pair("Dance", "en/genres/Dance"),
            Pair("Feminine", "en/genres/Feminine"),
            Pair("Best, Omnibus", "en/genres/Best,%20Omnibus"),
            Pair("Whites", "en/genres/Whites"),
            Pair("Flight Attendant", "en/genres/Flight%20Attendant"),
            Pair("Harem", "en/genres/Harem"),
            Pair("Foreign Actress", "en/genres/Foreign%20Actress"),
            Pair("Physical Education", "en/genres/Physical%20Education"),
            Pair("Bronze", "en/genres/Bronze"),
            Pair("Female Investigator", "en/genres/Female%20Investigator"),
            Pair("Transsexuals", "en/genres/Transsexuals"),
            Pair("Model", "en/genres/Model"),
            Pair("Baby Face", "en/genres/Baby%20Face"),
            Pair("Doggy Style", "en/genres/Doggy%20Style"),
            Pair("Shaving", "en/genres/Shaving"),
            Pair("Bitch", "en/genres/Bitch"),
            Pair("Bloomers", "en/genres/Bloomers"),
            Pair("One Piece Dress", "en/genres/One%20Piece%20Dress"),
            Pair("Knee Socks", "en/genres/Knee%20Socks"),
            Pair("Thanks Offering", "en/genres/Thanks%20Offering"),
            Pair("Cute Little Boy", "en/genres/Cute%20Little%20Boy"),
            Pair("Delivery-Only Amateur", "en/genres/Delivery-Only%20Amateur"),
            Pair("Other", "en/genres/Other"),
            Pair("Bubble Bath", "en/genres/Bubble%20Bath"),
            Pair("Tickle", "en/genres/Tickle"),
            Pair("High School Girl", "en/genres/High%20School%20Girl"),
            Pair("Sister", "en/genres/Sister"),
            Pair("Extreme Orgasm", "en/genres/Extreme%20Orgasm"),
            Pair("Breast Milk", "en/genres/Breast%20Milk"),
            Pair("M Female", "en/genres/M%20Female"),
            Pair("Pregnant Woman", "en/genres/Pregnant%20Woman"),
            Pair("Indie", "en/genres/Indie"),
            Pair("Homosexual", "en/genres/Homosexual"),
            Pair("Vr", "en/genres/Vr"),
            Pair("Drink Urine", "en/genres/Drink%20Urine"),
            Pair("Racing Girl", "en/genres/Racing%20Girl"),
            Pair("Femdom Slave", "en/genres/Femdom%20Slave"),
            Pair("Heaven Tv", "en/genres/Heaven%20Tv"),
            Pair("Secretary", "en/genres/Secretary"),
            Pair("Insult", "en/genres/Insult"),
            Pair("Hot Girl", "en/genres/Hot%20Girl"),
            Pair("Small Breasts", "en/genres/Small%20Breasts"),
            Pair("Rape", "en/genres/Rape"),
            Pair("Thirty", "en/genres/Thirty"),
            Pair("Lolita", "en/genres/Lolita"),
            Pair("Female Boss", "en/genres/Female%20Boss"),
            Pair("Foreign Object Penetration", "en/genres/Foreign%20Object%20Penetration"),
            Pair("Hit On Boys", "en/genres/Hit%20On%20Boys"),
            Pair("Stool", "en/genres/Stool"),
            Pair("Hysteroscope", "en/genres/Hysteroscope"),
            Pair("Young Wife", "en/genres/Young%20Wife"),
            Pair("Defecation", "en/genres/Defecation"),
            Pair("Gang Rape", "en/genres/Gang%20Rape"),
            Pair("Anchorwoman", "en/genres/Anchorwoman"),
            Pair("High Quality Vr", "en/genres/High%20Quality%20Vr"),
            Pair("Similar", "en/genres/Similar"),
            Pair("Transsexuals", "en/genres/Transsexuals"),
            Pair("Catwoman", "en/genres/Catwoman"),
            Pair("Bathtub", "en/genres/Bathtub"),
            Pair("Dildo", "en/genres/Dildo"),
            Pair("Limited Time", "en/genres/Limited%20Time"),
            Pair("Fist", "en/genres/Fist"),
            Pair("Dating", "en/genres/Dating"),
            Pair("Cuckold", "en/genres/Cuckold"),
            Pair("Original", "en/genres/Original"),
            Pair("Lecturer", "en/genres/Lecturer"),
            Pair("Esthetic Massage", "en/genres/Esthetic%20Massage"),
            Pair("Childhood", "en/genres/Childhood"),
            Pair("Uterus", "en/genres/Uterus"),
            Pair("Pregnant", "en/genres/Pregnant"),
            Pair("Entertainer", "en/genresentertainer"),
            Pair("Long Hair", "en/genres/Long%20Hair"),
            Pair("Petite", "en/genres/Petite"),
            Pair("First Shot", "en/genres/First%20Shot"),
            Pair("Muscle", "en/genres/Muscle"),
            Pair("Outdoors", "en/genres/Outdoors"),
            Pair("Naked Apron", "en/genres/Naked%20Apron"),
            Pair("Male Squirting", "en/genres/Male%20Squirting"),
            Pair("Hotel Owner", "en/genres/Hotel%20Owner"),
            Pair("Molester", "en/genres/Molester"),
            Pair("Artist", "en/genres/Artist"),
            Pair("Bunny Girl", "en/genres/Bunny%20Girl"),
            Pair("Travel", "en/genres/Travel"),
            Pair("Racing Girl", "en/genres/Racing%20Girl"),
            Pair("Asian Actress", "en/genres/Asian%20Actress"),
            Pair("Tentacle", "en/genres/Tentacle"),
            Pair("Proud Pussy", "en/genres/Proud%20Pussy"),
            Pair("Subordinate Or Colleague", "en/genres/Subordinate%20Or%20Colleague"),
            Pair("With Bonus Video Only For Mgs", "en/genres/With%20Bonus%20Video%20Only%20For%20Mgs"),
            Pair("Business Clothing", "en/genres/Business%20Clothing"),
            Pair("Premature Ejaculation", "en/genres/Premature%20Ejaculation"),
            Pair("Friend", "en/genres/Friend"),
            Pair("Shame And Humiliation", "en/genres/Shame%20And%20Humiliation"),
            Pair("Big Breasts", "en/genres/Big%20Breasts"),
            Pair("Short Hair", "en/genres/Short%20Hair"),
            Pair("Dildo", "en/genres/Dildo"),
            Pair("Limited Time", "en/genres/Limited%20Time"),
            Pair("Fist", "en/genres/Fist"),
            Pair("Dating", "en/genres/Dating"),
            Pair("Cuckold", "en/genres/Cuckold"),
            Pair("Original", "en/genres/Original"),
            Pair("Lecturer", "en/genres/Lecturer"),
            Pair("Esthetic Massage", "en/genres/Esthetic%20Massage"),
            Pair("Childhood", "en/genres/Childhood"),
            Pair("Uterus", "en/genres/Uterus"),
            Pair("Pregnant", "en/genres/Pregnant"),
            Pair("Entertainer", "en/genresentertainer"),
            Pair("Long Hair", "en/genres/Long%20Hair"),
            Pair("Petite", "en/genres/Petite"),
            Pair("First Shot", "en/genres/First%20Shot"),
            Pair("Muscle", "en/genres/Muscle"),
            Pair("Outdoors", "en/genres/Outdoors"),
            Pair("Naked Apron", "en/genres/Naked%20Apron"),
            Pair("Male Squirting", "en/genres/Male%20Squirting"),
            Pair("Hotel Owner", "en/genres/Hotel%20Owner"),
            Pair("Molester", "en/genres/Molester"),
            Pair("Artist", "en/genres/Artist"),
            Pair("Bunny Girl", "en/genres/Bunny%20Girl"),
            Pair("Travel", "en/genres/Travel"),
            Pair("Racing Girl", "en/genres/Racing%20Girl"),
            Pair("Asian Actress", "en/genres/Asian%20Actress"),
            Pair("Tentacle", "en/genres/Tentacle"),
            Pair("Proud Pussy", "en/genres/Proud%20Pussy"),
            Pair("Subordinate Or Colleague", "en/genres/Subordinate%20Or%20Colleague"),
            Pair("With Bonus Video Only For Mgs", "en/genres/With%20Bonus%20Video%20Only%20For%20Mgs"),
            Pair("Business Clothing", "en/genres/Business%20Clothing"),
            Pair("Premature Ejaculation", "en/genres/Premature%20Ejaculation"),
            Pair("Friend", "en/genres/Friend"),
            Pair("Shame And Humiliation", "en/genres/Shame%20And%20Humiliation"),
            Pair("Big Breasts", "en/genres/Big%20Breasts"),
            Pair("Short Hair", "en/genres/Short%20Hair"),
            Pair("Waitress", "en/genres/Waitress"),
            Pair("Clinic", "en/genres/Clinic"),
            Pair("Exposure", "en/genres/Exposure"),
            Pair("Kimono / Yukata", "en/genres/Kimono%20/%20Yukata"),
            Pair("Lewd Nasty Lady", "en/genres/Lewd%20Nasty%20Lady"),
            Pair("Bubble Socks", "en/genres/Bubble%20Socks"),
            Pair("Fantasy", "en/genres/Fantasy"),
            Pair("Idol", "en/genres/Idol"),
            Pair("Time Stops", "en/genres/Time%20Stops"),
        )
    }
}

class SortFilter : AnimeFilter.Select<String>(
    "Sort by",
    arrayOf(
        "Default",
        "Release date",
        "Recent update",
        "Today views",
        "Weekly views",
        "Monthly views",
        "Total views",
    )
) {
    companion object {
        val SORT_QUERIES = arrayOf(
            "",
            "released_at",
            "published_at",
            "today_views",
            "weekly_views",
            "monthly_views",
            "views",
        )
    }
}

class TriGenre(val display: String, val slug: String) : AnimeFilter.TriState(display)

class MultiGenreFilter : AnimeFilter.Group<AnimeFilter.TriState>(
    "Genres (Multi - Slow)",
    listOf(
            TriGenre("Uncensored Leak", "en/uncensored-leak"),
        TriGenre("HD", "en/genres/hd"),
        TriGenre("Exclusive", "en/genres/exclusive"),
        TriGenre("Creampie", "en/genres/Creampie"),
        TriGenre("Big Breasts", "en/genres/Big%20Breasts"),
        TriGenre("Individual", "en/genres/Individual"),
        TriGenre("Wife", "en/genres/Wife"),
        TriGenre("Mature Woman", "en/genres/Mature%20Woman"),
        TriGenre("Ordinary Person", "en/genres/Ordinary%20Person"),
        TriGenre("Pretty Girl", "en/genres/Pretty%20Girl"),
        TriGenre("Ride", "en/genres/Ride"),
        TriGenre("Oral Sex", "en/genres/Oral%20Sex"),
        TriGenre("Orgy", "en/genres/Orgy"),
        TriGenre("Slim Pixelated", "en/genres/Slim%20Pixelated"),
        TriGenre("4 Hours Or More", "en/genres/4%20Hours%20Or%20More"),
        TriGenre("Slut", "en/genres/Slut"),
        TriGenre("Collection", "en/genres/Collection"),
        TriGenre("High School Girl", "en/genres/High%20School%20Girl"),
        TriGenre("Squirting", "en/genres/Squirting"),
        TriGenre("Fetish", "en/genres/Fetish"),
        TriGenre("Selfie", "en/genres/Selfie"),
        TriGenre("Tit Job", "en/genres/Tit%20Job"),
        TriGenre("Planning", "en/genres/Planning"),
        TriGenre("Incest", "en/genres/Incest"),
        TriGenre("Hit On Girls", "en/genres/Hit%20On%20Girls"),
        TriGenre("Sneak Shots", "en/genres/Sneak%20Shots"),
        TriGenre("Slim", "en/genres/Slim"),
        TriGenre("Bukkake", "en/genres/Bukkake"),
        TriGenre("Beautiful Breasts", "en/genres/Beautiful%20Breasts"),
        TriGenre("Masturbate", "en/genres/Masturbate"),
        TriGenre("Masturbation", "en/genres/Masturbation"),
        TriGenre("Restraint", "en/genres/Restraint"),
        TriGenre("Promiscuous", "en/genres/Promiscuous"),
        TriGenre("Lesbian", "en/genres/Lesbian"),
        TriGenre("Ntr", "en/genres/Ntr"),
        TriGenre("Sister", "en/genres/Sister"),
        TriGenre("Plot", "en/genres/Plot"),
        TriGenre("Cosplay", "en/genres/Cosplay"),
        TriGenre("Humiliation", "en/genres/Humiliation"),
        TriGenre("Documentary", "en/genres/Documentary"),
        TriGenre("Hot Girl", "en/genres/Hot%20Girl"),
        TriGenre("Ol", "en/genres/Ol"),
        TriGenre("Uniform", "en/genres/Uniform"),
        TriGenre("Fingering", "en/genres/Fingering"),
        TriGenre("Vibrator", "en/genres/Vibrator"),
        TriGenre("Adultery", "en/genres/Adultery"),
        TriGenre("Cunnilingus", "en/genres/Cunnilingus"),
        TriGenre("Delusion", "en/genres/Delusion"),
        TriGenre("Female College Student", "en/genres/Female%20College%20Student"),
        TriGenre("Sm", "en/genres/Sm"),
        TriGenre("Shame", "en/genres/Shame"),
        TriGenre("Anus", "en/genres/Anus"),
        TriGenre("Uniform", "en/genres/Uniform"),
        TriGenre("Petite", "en/genres/Petite"),
        TriGenre("Shaving", "en/genres/Shaving"),
        TriGenre("Subjective Perspective", "en/genres/Subjective%20Perspective"),
        TriGenre("Prostitute", "en/genres/Prostitute"),
        TriGenre("Various Occupations", "en/genres/Various%20Occupations"),
        TriGenre("Mother", "en/genres/Mother"),
        TriGenre("Vibrator", "en/genres/Vibrator"),
        TriGenre("Toy", "en/genres/Toy"),
        TriGenre("Promiscuity", "en/genres/Promiscuity"),
        TriGenre("Outdoor Exposure", "en/genres/Outdoor%20Exposure"),
        TriGenre("Butt Fetish", "en/genres/Butt%20Fetish"),
        TriGenre("Pantyhose", "en/genres/Pantyhose"),
        TriGenre("Debut", "en/genres/Debut"),
        TriGenre("Urinate", "en/genres/Urinate"),
        TriGenre("Dirty Talk", "en/genres/Dirty%20Talk"),
        TriGenre("Massage", "en/genres/Massage"),
        TriGenre("Underwear", "en/genres/Underwear"),
        TriGenre("Big Ass", "en/genres/Big%20Ass"),
        TriGenre("Forced Blowjob", "en/genres/Forced%20Blowjob"),
        TriGenre("Sailor Suit", "en/genres/Sailor%20Suit"),
        TriGenre("Swimsuit", "en/genres/Swimsuit"),
        TriGenre("Delivery Only", "en/genres/Delivery%20Only"),
        TriGenre("Female Teacher", "en/genres/Female%20Teacher"),
        TriGenre("Kimono", "en/genres/Kimono"),
        TriGenre("Swallow Sperm", "en/genres/Swallow%20Sperm"),
        TriGenre("69", "en/genres/69"),
        TriGenre("Small Breasts", "en/genres/Small%20Breasts"),
        TriGenre("Elder Sister", "en/genres/Elder%20Sister"),
        TriGenre("Young Wife", "en/genres/Young%20Wife"),
        TriGenre("Nurse", "en/genres/Nurse"),
        TriGenre("Massage Oil", "en/genres/Massage%20Oil"),
        TriGenre("Group Bukkake", "en/genres/Group%20Bukkake"),
        TriGenre("Tied Up", "en/genres/Tied%20Up"),
        TriGenre("Fat Girl", "en/genres/Fat%20Girl"),
        TriGenre("Rejuvenation Massage", "en/genres/Rejuvenation%20Massage"),
        TriGenre("Short Skirt", "en/genres/Short%20Skirt"),
        TriGenre("Ultra Slim Pixelated", "en/genres/Ultra%20Slim%20Pixelated"),
        TriGenre("Contribution", "en/genres/Contribution"),
        TriGenre("Nice Ass", "en/genres/Nice%20Ass"),
        TriGenre("Foot Fetish", "en/genres/Foot%20Fetish"),
        TriGenre("Full Hd (Fhd)", "en/genres/Full%20Hd%20%28Fhd%29"),
        TriGenre("Glasses Girl", "en/genres/Glasses%20Girl"),
        TriGenre("Kiss", "en/genres/Kiss"),
        TriGenre("4K", "en/genres/4K"),
        TriGenre("Close Up", "en/genres/Close%20Up"),
        TriGenre("Big Breasts", "en/genres/Big%20Breasts"),
        TriGenre("Tied Up", "en/genres/Tied%20Up"),
        TriGenre("Big Breast Fetish", "en/genres/Big%20Breast%20Fetish"),
        TriGenre("Swimsuit", "en/genres/Swimsuit"),
        TriGenre("Sportswear", "en/genres/Sportswear"),
        TriGenre("Virgin", "en/genres/Virgin"),
        TriGenre("Vibrating Egg", "en/genres/Vibrating%20Egg"),
        TriGenre("Aphrodisiac", "en/genres/Aphrodisiac"),
        TriGenre("Lesbian Kiss", "en/genres/Lesbian%20Kiss"),
        TriGenre("Mini Skirt", "en/genres/Mini%20Skirt"),
        TriGenre("White Skin", "en/genres/White%20Skin"),
        TriGenre("M Male", "en/genres/M%20Male"),
        TriGenre("Couple", "en/genres/Couple"),
        TriGenre("Hot Spring", "en/genres/Hot%20Spring"),
        TriGenre("Maid", "en/genres/Maid"),
        TriGenre("Face Ride", "en/genres/Face%20Ride"),
        TriGenre("Imprisonment", "en/genres/Imprisonment"),
        TriGenre("Footjob", "en/genres/Footjob"),
        TriGenre("Fighting", "en/genres/Fighting"),
        TriGenre("Tall Lady", "en/genres/Tall%20Lady"),
        TriGenre("Female Warrior", "en/genres/Female%20Warrior"),
        TriGenre("Artist", "en/genres/Artist"),
        TriGenre("Science Fiction", "en/genres/Science%20Fiction"),
        TriGenre("Mischief", "en/genres/Mischief"),
        TriGenre("Actress Collection", "en/genres/Actress%20Collection"),
        TriGenre("Married Woman", "en/genres/Married%20Woman"),
        TriGenre("Sweating", "en/genres/Sweating"),
        TriGenre("Black Male Actor", "en/genres/Black%20Male%20Actor"),
        TriGenre("Stepmother", "en/genres/Stepmother"),
        TriGenre("Petite", "en/genres/Petite"),
        TriGenre("Beautiful Legs", "en/genres/Beautiful%20Legs"),
        TriGenre("Private Teacher", "en/genres/Private%20Teacher"),
        TriGenre("Big Pennis", "en/genres/Big%20Pennis"),
        TriGenre("Super Breasts", "en/genres/Super%20Breasts"),
        TriGenre("Advertising Idol", "en/genres/Advertising%20Idol"),
        TriGenre("Torture", "en/genres/Torture"),
        TriGenre("Emmanuel", "en/genres/Emmanuel"),
        TriGenre("Anal Sex", "en/genres/Anal%20Sex"),
        TriGenre("Black Hair", "en/genres/Black%20Hair"),
        TriGenre("Beautiful Breasts", "en/genres/Beautiful%20Breasts"),
        TriGenre("Erotic Photo", "en/genres/Erotic%20Photo"),
        TriGenre("Widow", "en/genres/Widow"),
        TriGenre("Gym Suit", "en/genres/Gym%20Suit"),
        TriGenre("Cruel", "en/genres/Cruel"),
        TriGenre("Sexy", "en/genres/Sexy"),
        TriGenre("Car Sex", "en/genres/Car%20Sex"),
        TriGenre("Multiple Stories", "en/genres/Multiple%20Stories"),
        TriGenre("Campus Story", "en/genres/Campus%20Story"),
        TriGenre("3P, 4P", "en/genres/3P,%204P"),
        TriGenre("Transgender", "en/genres/Transgender"),
        TriGenre("Slim", "en/genres/Slim"),
        TriGenre("Female Doctor", "en/genres/Female%20Doctor"),
        TriGenre("In Love", "en/genres/In%20Love"),
        TriGenre("Fighter", "en/genres/Fighter"),
        TriGenre("Fantasy", "en/genres/Fantasy"),
        TriGenre("Pure", "en/genres/Pure"),
        TriGenre("Virgin", "en/genres/Virgin"),
        TriGenre("Instant Sex", "en/genres/Instant%20Sex"),
        TriGenre("Missy", "en/genres/Missy"),
        TriGenre("Enema", "en/genresenema"),
        TriGenre("Dance", "en/genres/Dance"),
        TriGenre("Feminine", "en/genres/Feminine"),
        TriGenre("Best, Omnibus", "en/genres/Best,%20Omnibus"),
        TriGenre("Whites", "en/genres/Whites"),
        TriGenre("Flight Attendant", "en/genres/Flight%20Attendant"),
        TriGenre("Harem", "en/genres/Harem"),
        TriGenre("Foreign Actress", "en/genres/Foreign%20Actress"),
        TriGenre("Physical Education", "en/genres/Physical%20Education"),
        TriGenre("Bronze", "en/genres/Bronze"),
        TriGenre("Female Investigator", "en/genres/Female%20Investigator"),
        TriGenre("Transsexuals", "en/genres/Transsexuals"),
        TriGenre("Model", "en/genres/Model"),
        TriGenre("Baby Face", "en/genres/Baby%20Face"),
        TriGenre("Doggy Style", "en/genres/Doggy%20Style"),
        TriGenre("Shaving", "en/genres/Shaving"),
        TriGenre("Bitch", "en/genres/Bitch"),
        TriGenre("Bloomers", "en/genres/Bloomers"),
        TriGenre("One Piece Dress", "en/genres/One%20Piece%20Dress"),
        TriGenre("Knee Socks", "en/genres/Knee%20Socks"),
        TriGenre("Thanks Offering", "en/genres/Thanks%20Offering"),
        TriGenre("Cute Little Boy", "en/genres/Cute%20Little%20Boy"),
        TriGenre("Delivery-Only Amateur", "en/genres/Delivery-Only%20Amateur"),
        TriGenre("Other", "en/genres/Other"),
        TriGenre("Bubble Bath", "en/genres/Bubble%20Bath"),
        TriGenre("Tickle", "en/genres/Tickle"),
        TriGenre("High School Girl", "en/genres/High%20School%20Girl"),
        TriGenre("Sister", "en/genres/Sister"),
        TriGenre("Extreme Orgasm", "en/genres/Extreme%20Orgasm"),
        TriGenre("Breast Milk", "en/genres/Breast%20Milk"),
        TriGenre("M Female", "en/genres/M%20Female"),
        TriGenre("Pregnant Woman", "en/genres/Pregnant%20Woman"),
        TriGenre("Indie", "en/genres/Indie"),
        TriGenre("Homosexual", "en/genres/Homosexual"),
        TriGenre("Vr", "en/genres/Vr"),
        TriGenre("Drink Urine", "en/genres/Drink%20Urine"),
        TriGenre("Racing Girl", "en/genres/Racing%20Girl"),
        TriGenre("Femdom Slave", "en/genres/Femdom%20Slave"),
        TriGenre("Heaven Tv", "en/genres/Heaven%20Tv"),
        TriGenre("Secretary", "en/genres/Secretary"),
        TriGenre("Insult", "en/genres/Insult"),
        TriGenre("Hot Girl", "en/genres/Hot%20Girl"),
        TriGenre("Small Breasts", "en/genres/Small%20Breasts"),
        TriGenre("Rape", "en/genres/Rape"),
        TriGenre("Thirty", "en/genres/Thirty"),
        TriGenre("Lolita", "en/genres/Lolita"),
        TriGenre("Female Boss", "en/genres/Female%20Boss"),
        TriGenre("Foreign Object Penetration", "en/genres/Foreign%20Object%20Penetration"),
        TriGenre("Hit On Boys", "en/genres/Hit%20On%20Boys"),
        TriGenre("Stool", "en/genres/Stool"),
        TriGenre("Hysteroscope", "en/genres/Hysteroscope"),
        TriGenre("Young Wife", "en/genres/Young%20Wife"),
        TriGenre("Defecation", "en/genres/Defecation"),
        TriGenre("Gang Rape", "en/genres/Gang%20Rape"),
        TriGenre("Anchorwoman", "en/genres/Anchorwoman"),
        TriGenre("High Quality Vr", "en/genres/High%20Quality%20Vr"),
        TriGenre("Similar", "en/genres/Similar"),
        TriGenre("Transsexuals", "en/genres/Transsexuals"),
        TriGenre("Catwoman", "en/genres/Catwoman"),
        TriGenre("Bathtub", "en/genres/Bathtub"),
        TriGenre("Dildo", "en/genres/Dildo"),
        TriGenre("Limited Time", "en/genres/Limited%20Time"),
        TriGenre("Fist", "en/genres/Fist"),
        TriGenre("Dating", "en/genres/Dating"),
        TriGenre("Cuckold", "en/genres/Cuckold"),
        TriGenre("Original", "en/genres/Original"),
        TriGenre("Lecturer", "en/genres/Lecturer"),
        TriGenre("Esthetic Massage", "en/genres/Esthetic%20Massage"),
        TriGenre("Childhood", "en/genres/Childhood"),
        TriGenre("Uterus", "en/genres/Uterus"),
        TriGenre("Pregnant", "en/genres/Pregnant"),
        TriGenre("Entertainer", "en/genresentertainer"),
        TriGenre("Long Hair", "en/genres/Long%20Hair"),
        TriGenre("Petite", "en/genres/Petite"),
        TriGenre("First Shot", "en/genres/First%20Shot"),
        TriGenre("Muscle", "en/genres/Muscle"),
        TriGenre("Outdoors", "en/genres/Outdoors"),
        TriGenre("Naked Apron", "en/genres/Naked%20Apron"),
        TriGenre("Male Squirting", "en/genres/Male%20Squirting"),
        TriGenre("Hotel Owner", "en/genres/Hotel%20Owner"),
        TriGenre("Molester", "en/genres/Molester"),
        TriGenre("Artist", "en/genres/Artist"),
        TriGenre("Bunny Girl", "en/genres/Bunny%20Girl"),
        TriGenre("Travel", "en/genres/Travel"),
        TriGenre("Racing Girl", "en/genres/Racing%20Girl"),
        TriGenre("Asian Actress", "en/genres/Asian%20Actress"),
        TriGenre("Tentacle", "en/genres/Tentacle"),
        TriGenre("Proud Pussy", "en/genres/Proud%20Pussy"),
        TriGenre("Subordinate Or Colleague", "en/genres/Subordinate%20Or%20Colleague"),
        TriGenre("With Bonus Video Only For Mgs", "en/genres/With%20Bonus%20Video%20Only%20For%20Mgs"),
        TriGenre("Business Clothing", "en/genres/Business%20Clothing"),
        TriGenre("Premature Ejaculation", "en/genres/Premature%20Ejaculation"),
        TriGenre("Friend", "en/genres/Friend"),
        TriGenre("Shame And Humiliation", "en/genres/Shame%20And%20Humiliation"),
        TriGenre("Big Breasts", "en/genres/Big%20Breasts"),
        TriGenre("Short Hair", "en/genres/Short%20Hair"),
        TriGenre("Dildo", "en/genres/Dildo"),
        TriGenre("Limited Time", "en/genres/Limited%20Time"),
        TriGenre("Fist", "en/genres/Fist"),
        TriGenre("Dating", "en/genres/Dating"),
        TriGenre("Cuckold", "en/genres/Cuckold"),
        TriGenre("Original", "en/genres/Original"),
        TriGenre("Lecturer", "en/genres/Lecturer"),
        TriGenre("Esthetic Massage", "en/genres/Esthetic%20Massage"),
        TriGenre("Childhood", "en/genres/Childhood"),
        TriGenre("Uterus", "en/genres/Uterus"),
        TriGenre("Pregnant", "en/genres/Pregnant"),
        TriGenre("Entertainer", "en/genresentertainer"),
        TriGenre("Long Hair", "en/genres/Long%20Hair"),
        TriGenre("Petite", "en/genres/Petite"),
        TriGenre("First Shot", "en/genres/First%20Shot"),
        TriGenre("Muscle", "en/genres/Muscle"),
        TriGenre("Outdoors", "en/genres/Outdoors"),
        TriGenre("Naked Apron", "en/genres/Naked%20Apron"),
        TriGenre("Male Squirting", "en/genres/Male%20Squirting"),
        TriGenre("Hotel Owner", "en/genres/Hotel%20Owner"),
        TriGenre("Molester", "en/genres/Molester"),
        TriGenre("Artist", "en/genres/Artist"),
        TriGenre("Bunny Girl", "en/genres/Bunny%20Girl"),
        TriGenre("Travel", "en/genres/Travel"),
        TriGenre("Racing Girl", "en/genres/Racing%20Girl"),
        TriGenre("Asian Actress", "en/genres/Asian%20Actress"),
        TriGenre("Tentacle", "en/genres/Tentacle"),
        TriGenre("Proud Pussy", "en/genres/Proud%20Pussy"),
        TriGenre("Subordinate Or Colleague", "en/genres/Subordinate%20Or%20Colleague"),
        TriGenre("With Bonus Video Only For Mgs", "en/genres/With%20Bonus%20Video%20Only%20For%20Mgs"),
        TriGenre("Business Clothing", "en/genres/Business%20Clothing"),
        TriGenre("Premature Ejaculation", "en/genres/Premature%20Ejaculation"),
        TriGenre("Friend", "en/genres/Friend"),
        TriGenre("Shame And Humiliation", "en/genres/Shame%20And%20Humiliation"),
        TriGenre("Big Breasts", "en/genres/Big%20Breasts"),
        TriGenre("Short Hair", "en/genres/Short%20Hair"),
        TriGenre("Waitress", "en/genres/Waitress"),
        TriGenre("Clinic", "en/genres/Clinic"),
        TriGenre("Exposure", "en/genres/Exposure"),
        TriGenre("Kimono / Yukata", "en/genres/Kimono%20/%20Yukata"),
        TriGenre("Lewd Nasty Lady", "en/genres/Lewd%20Nasty%20Lady"),
        TriGenre("Bubble Socks", "en/genres/Bubble%20Socks"),
        TriGenre("Fantasy", "en/genres/Fantasy"),
        TriGenre("Idol", "en/genres/Idol"),
        TriGenre("Time Stops", "en/genres/Time%20Stops"),
    ),
)

data class FilterSearchParams(
    val include: List<Pair<String, String>> = emptyList(),
    val exclude: List<Pair<String, String>> = emptyList(),
)

fun getFilters(): AnimeFilterList {
    return AnimeFilterList(
        SingleGenreFilter(),
        SortFilter(),
        AnimeFilter.Separator(),
        MultiGenreFilter(),
        AnimeFilter.Separator(),
        AnimeFilter.Header("Single Genre: Fast server-side filtering"),
        AnimeFilter.Header("Multi-Genre: Client-side filtering (slow)"),
        AnimeFilter.Header("✓ = Include | ✗ = Exclude | Empty = Ignore"),
        AnimeFilter.Header("Multi-genre uses first tag as base search"),
    )
}

internal fun getSearchParameters(filters: AnimeFilterList): FilterSearchParams {
    val include = mutableListOf<Pair<String, String>>()
    val exclude = mutableListOf<Pair<String, String>>()
    val multiGenreFilter = filters.find { it is MultiGenreFilter } as? MultiGenreFilter
    multiGenreFilter?.state?.forEach { filter ->
        if (filter is TriGenre) {
            when (filter.state) {
                AnimeFilter.TriState.STATE_INCLUDE -> include.add(Pair(filter.display, filter.slug))
                AnimeFilter.TriState.STATE_EXCLUDE -> exclude.add(Pair(filter.display, filter.slug))
                else -> {}
            }
        }
    }
    return FilterSearchParams(include, exclude)
}
