package eu.kanade.tachiyomi.animeextension.all.missav

import eu.kanade.tachiyomi.animesource.model.AnimeFilter
import eu.kanade.tachiyomi.animesource.model.AnimeFilterList

class SortFilter : AnimeFilter.Select<String>(
    "Sort by",
    arrayOf(
        "Release date",
        "Recent update",
        "Today views",
        "Weekly views",
        "Monthly views",
        "Total views",
    ),
) {
    companion object {
        val SORT = listOf(
            Pair("Release date", "released_at"),
            Pair("Recent update", "published_at"),
            Pair("Today views", "today_views"),
            Pair("Weekly views", "weekly_views"),
            Pair("Monthly views", "monthly_views"),
            Pair("Total views", "views"),
        )
    }
}

class GenreList : AnimeFilter.Select<String>(
    "Genres (Single)",
    arrayOf(
        "",
        "Uncensored Leak",
        "Hd",
        "Exclusive",
        "Creampie",
        "Big Breasts",
        "Individual",
        "Wife",
        "Mature Woman",
        "Ordinary Person",
        "Pretty Girl",
        "Ride",
        "Oral Sex",
        "Orgy",
        "Slim Pixelated",
        "4 Hours Or More",
        "Slut",
        "Collection",
        "High School Girl",
        "Squirting",
        "Fetish",
        "Selfie",
        "Tit Job",
        "Planning",
        "Incest",
        "Hit On Girls",
        "Sneak Shots",
        "Slim",
        "Bukkake",
        "Beautiful Breasts",
        "Masturbate",
        "Masturbation",
        "Restraint",
        "Promiscuous",
        "Lesbian",
        "Ntr",
        "Sister",
        "Plot",
        "Cosplay",
        "Humiliation",
        "Documentary",
        "Hot Girl",
        "Ol",
        "Uniform",
        "Fingering",
        "Vibrator",
        "Adultery",
        "Cunnilingus",
        "Delusion",
        "Female College Student",
        "Sm",
        "Shame",
        "Anus",
        "Uniform",
        "Petite",
        "Shaving",
        "Subjective Perspective",
        "Prostitute",
        "Various Occupations",
        "Mother",
        "Vibrator",
        "Toy",
        "Promiscuity",
        "Outdoor Exposure",
        "Butt Fetish",
        "Pantyhose",
        "Debut",
        "Urinate",
        "Dirty Talk",
        "Massage",
        "Underwear",
        "Big Ass",
        "Forced Blowjob",
        "Sailor Suit",
        "Swimsuit",
        "Delivery Only",
        "Female Teacher",
        "Kimono",
        "Swallow Sperm",
        "69",
        "Small Breasts",
        "Elder Sister",
        "Young Wife",
        "Nurse",
        "Massage Oil",
        "Group Bukkake",
        "Tied Up",
        "Fat Girl",
        "Rejuvenation Massage",
        "Short Skirt",
        "Ultra Slim Pixelated",
        "Contribution",
        "Nice Ass",
        "Foot Fetish",
        "Full Hd (Fhd)",
        "Glasses Girl",
        "Kiss",
        "4K",
        "Close Up",
        "Big Breasts",
        "Tied Up",
        "Big Breast Fetish",
        "Swimsuit",
        "Sportswear",
        "Virgin",
        "Vibrating Egg",
        "Aphrodisiac",
        "Lesbian Kiss",
        "Mini Skirt",
        "White Skin",
        "M Male",
        "Couple",
        "Hot Spring",
        "Maid",
        "Face Ride",
        "Imprisonment",
        "Footjob",
        "Fighting",
        "Tall Lady",
        "Female Warrior",
        "Artist",
        "Science Fiction",
        "Mischief",
        "Actress Collection",
        "Married Woman",
        "Sweating",
        "Black Male Actor",
        "Stepmother",
        "Petite",
        "Beautiful Legs",
        "Private Teacher",
        "Big Pennis",
        "Super Breasts",
        "Advertising Idol",
        "Torture",
        "Emmanuel",
        "Anal Sex",
        "Black Hair",
        "Beautiful Breasts",
        "Erotic Photo",
        "Widow",
        "Gym Suit",
        "Cruel",
        "Sexy",
        "Car Sex",
        "Multiple Stories",
        "Campus Story",
        "3P, 4P",
        "Transgender",
        "Slim",
        "Female Doctor",
        "In Love",
        "Fighter",
        "Fantasy",
        "Pure",
        "Virgin",
        "Instant Sex",
        "Missy",
        "Enema",
        "Dance",
        "Feminine",
        "Best, Omnibus",
        "Whites",
        "Flight Attendant",
        "Harem",
        "Foreign Actress",
        "Physical Education",
        "Bronze",
        "Female Investigator",
        "Transsexuals",
        "Model",
        "Baby Face",
        "Doggy Style",
        "Shaving",
        "Bitch",
        "Bloomers",
        "One Piece Dress",
        "Knee Socks",
        "Thanks Offering",
        "Cute Little Boy",
        "Delivery-Only Amateur",
        "Other",
        "Bubble Bath",
        "Tickle",
        "High School Girl",
        "Sister",
        "Extreme Orgasm",
        "Breast Milk",
        "M Female",
        "Pregnant Woman",
        "Indie",
        "Homosexual",
        "Vr",
        "Drink Urine",
        "Racing Girl",
        "Femdom Slave",
        "Heaven Tv",
        "Secretary",
        "Insult",
        "Hot Girl",
        "Small Breasts",
        "Rape",
        "Thirty",
        "Lolita",
        "Female Boss",
        "Foreign Object Penetration",
        "Hit On Boys",
        "Stool",
        "Hysteroscope",
        "Young Wife",
        "Defecation",
        "Gang Rape",
        "Anchorwoman",
        "High Quality Vr",
        "Similar",
        "Transsexuals",
        "Catwoman",
        "Bathtub",
        "Dildo",
        "Limited Time",
        "Fist",
        "Dating",
        "Cuckold",
        "Original",
        "Lecturer",
        "Esthetic Massage",
        "Childhood",
        "Uterus",
        "Pregnant",
        "Entertainer",
        "Long Hair",
        "Petite",
        "First Shot",
        "Muscle",
        "Outdoors",
        "Naked Apron",
        "Male Squirting",
        "Hotel Owner",
        "Molester",
        "Artist",
        "Bunny Girl",
        "Travel",
        "Racing Girl",
        "Asian Actress",
        "Tentacle",
        "Proud Pussy",
        "Subordinate Or Colleague",
        "With Bonus Video Only For Mgs",
        "Business Clothing",
        "Premature Ejaculation",
        "Friend",
        "Shame And Humiliation",
        "Big Breasts",
        "Short Hair",
        "Dildo",
        "Limited Time",
        "Fist",
        "Dating",
        "Cuckold",
        "Original",
        "Lecturer",
        "Esthetic Massage",
        "Childhood",
        "Uterus",
        "Pregnant",
        "Entertainer",
        "Long Hair",
        "Petite",
        "First Shot",
        "Muscle",
        "Outdoors",
        "Naked Apron",
        "Male Squirting",
        "Hotel Owner",
        "Molester",
        "Artist",
        "Bunny Girl",
        "Travel",
        "Racing Girl",
        "Asian Actress",
        "Tentacle",
        "Proud Pussy",
        "Subordinate Or Colleague",
        "With Bonus Video Only For Mgs",
        "Business Clothing",
        "Premature Ejaculation",
        "Friend",
        "Shame And Humiliation",
        "Big Breasts",
        "Short Hair",
        "Waitress",
        "Clinic",
        "Exposure",
        "Kimono / Yukata",
        "Lewd Nasty Lady",
        "Bubble Socks",
        "Fantasy",
        "Idol",
        "Time Stops",
    ),
) {
    companion object {
        val GENRES = listOf(
            Pair("", ""),
            Pair("Uncensored Leak", "en/uncensored-leak"),
            Pair("Hd", "en/genres/Hd"),
            Pair("Exclusive", "en/genres/Exclusive"),
            Pair("Creampie", "en/genres/Creampie"),
            Pair("Big Breasts", "en/genres/Big%20Breasts"),
            Pair("Individual", "en/genres/Individual"),
            Pair("Wife", "en/genres/Wife"),
            Pair("Mature Woman", "en/genres/Mature%20Woman"),
            Pair("Ordinary Person", "en/genres/Ordinary%20Person"),
            Pair("Pretty Girl", "en/genres/Pretty%20Girl"),
            Pair("Ride", "en/genres/Ride"),
            Pair("Oral Sex", "en/genres/Oral%20Sex"),
            Pair("Orgy", "en/genres/Orgy"),
            Pair("Slim Pixelated", "en/genres/Slim%20Pixelated"),
            Pair("4 Hours Or More", "en/genres/4%20Hours%20Or%20More"),
            Pair("Slut", "en/genres/Slut"),
            Pair("Collection", "en/genres/Collection"),
            Pair("High School Girl", "en/genres/High%20School%20Girl"),
            Pair("Squirting", "en/genres/Squirting"),
            Pair("Fetish", "en/genres/Fetish"),
            Pair("Selfie", "en/genres/Selfie"),
            Pair("Tit Job", "en/genres/Tit%20Job"),
            Pair("Planning", "en/genres/Planning"),
            Pair("Incest", "en/genres/Incest"),
            Pair("Hit On Girls", "en/genres/Hit%20On%20Girls"),
            Pair("Sneak Shots", "en/genres/Sneak%20Shots"),
            Pair("Slim", "en/genres/Slim"),
            Pair("Bukkake", "en/genres/Bukkake"),
            Pair("Beautiful Breasts", "en/genres/Beautiful%20Breasts"),
            Pair("Masturbate", "en/genres/Masturbate"),
            Pair("Masturbation", "en/genres/Masturbation"),
            Pair("Restraint", "en/genres/Restraint"),
            Pair("Promiscuous", "en/genres/Promiscuous"),
            Pair("Lesbian", "en/genres/Lesbian"),
            Pair("Ntr", "en/genres/Ntr"),
            Pair("Sister", "en/genres/Sister"),
            Pair("Plot", "en/genres/Plot"),
            Pair("Cosplay", "en/genres/Cosplay"),
            Pair("Humiliation", "en/genres/Humiliation"),
            Pair("Documentary", "en/genres/Documentary"),
            Pair("Hot Girl", "en/genres/Hot%20Girl"),
            Pair("Ol", "en/genres/Ol"),
            Pair("Uniform", "en/genres/Uniform"),
            Pair("Fingering", "en/genres/Fingering"),
            Pair("Vibrator", "en/genres/Vibrator"),
            Pair("Adultery", "en/genres/Adultery"),
            Pair("Cunnilingus", "en/genres/Cunnilingus"),
            Pair("Delusion", "en/genres/Delusion"),
            Pair("Female College Student", "en/genres/Female%20College%20Student"),
            Pair("Sm", "en/genres/Sm"),
            Pair("Shame", "en/genres/Shame"),
            Pair("Anus", "en/genres/Anus"),
            Pair("Uniform", "en/genres/Uniform"),
            Pair("Petite", "en/genres/Petite"),
            Pair("Shaving", "en/genres/Shaving"),
            Pair("Subjective Perspective", "en/genres/Subjective%20Perspective"),
            Pair("Prostitute", "en/genres/Prostitute"),
            Pair("Various Occupations", "en/genres/Various%20Occupations"),
            Pair("Mother", "en/genres/Mother"),
            Pair("Vibrator", "en/genres/Vibrator"),
            Pair("Toy", "en/genres/Toy"),
            Pair("Promiscuity", "en/genres/Promiscuity"),
            Pair("Outdoor Exposure", "en/genres/Outdoor%20Exposure"),
            Pair("Butt Fetish", "en/genres/Butt%20Fetish"),
            Pair("Pantyhose", "en/genres/Pantyhose"),
            Pair("Debut", "en/genres/Debut"),
            Pair("Urinate", "en/genres/Urinate"),
            Pair("Dirty Talk", "en/genres/Dirty%20Talk"),
            Pair("Massage", "en/genres/Massage"),
            Pair("Underwear", "en/genres/Underwear"),
            Pair("Big Ass", "en/genres/Big%20Ass"),
            Pair("Forced Blowjob", "en/genres/Forced%20Blowjob"),
            Pair("Sailor Suit", "en/genres/Sailor%20Suit"),
            Pair("Swimsuit", "en/genres/Swimsuit"),
            Pair("Delivery Only", "en/genres/Delivery%20Only"),
            Pair("Female Teacher", "en/genres/Female%20Teacher"),
            Pair("Kimono", "en/genres/Kimono"),
            Pair("Swallow Sperm", "en/genres/Swallow%20Sperm"),
            Pair("69", "en/genres/69"),
            Pair("Small Breasts", "en/genres/Small%20Breasts"),
            Pair("Elder Sister", "en/genres/Elder%20Sister"),
            Pair("Young Wife", "en/genres/Young%20Wife"),
            Pair("Nurse", "en/genres/Nurse"),
            Pair("Massage Oil", "en/genres/Massage%20Oil"),
            Pair("Group Bukkake", "en/genres/Group%20Bukkake"),
            Pair("Tied Up", "en/genres/Tied%20Up"),
            Pair("Fat Girl", "en/genres/Fat%20Girl"),
            Pair("Rejuvenation Massage", "en/genres/Rejuvenation%20Massage"),
            Pair("Short Skirt", "en/genres/Short%20Skirt"),
            Pair("Ultra Slim Pixelated", "en/genres/Ultra%20Slim%20Pixelated"),
            Pair("Contribution", "en/genres/Contribution"),
            Pair("Nice Ass", "en/genres/Nice%20Ass"),
            Pair("Foot Fetish", "en/genres/Foot%20Fetish"),
            Pair("Full Hd (Fhd)", "en/genres/Full%20Hd%20%28Fhd%29"),
            Pair("Glasses Girl", "en/genres/Glasses%20Girl"),
            Pair("Kiss", "en/genres/Kiss"),
            Pair("4K", "en/genres/4K"),
            Pair("Close Up", "en/genres/Close%20Up"),
            Pair("Big Breasts", "en/genres/Big%20Breasts"),
            Pair("Tied Up", "en/genres/Tied%20Up"),
            Pair("Big Breast Fetish", "en/genres/Big%20Breast%20Fetish"),
            Pair("Swimsuit", "en/genres/Swimsuit"),
            Pair("Sportswear", "en/genres/Sportswear"),
            Pair("Virgin", "en/genres/Virgin"),
            Pair("Vibrating Egg", "en/genres/Vibrating%20Egg"),
            Pair("Aphrodisiac", "en/genres/Aphrodisiac"),
            Pair("Lesbian Kiss", "en/genres/Lesbian%20Kiss"),
            Pair("Mini Skirt", "en/genres/Mini%20Skirt"),
            Pair("White Skin", "en/genres/White%20Skin"),
            Pair("M Male", "en/genres/M%20Male"),
            Pair("Couple", "en/genres/Couple"),
            Pair("Hot Spring", "en/genres/Hot%20Spring"),
            Pair("Maid", "en/genres/Maid"),
            Pair("Face Ride", "en/genres/Face%20Ride"),
            Pair("Imprisonment", "en/genres/Imprisonment"),
            Pair("Footjob", "en/genres/Footjob"),
            Pair("Fighting", "en/genres/Fighting"),
            Pair("Tall Lady", "en/genres/Tall%20Lady"),
            Pair("Female Warrior", "en/genres/Female%20Warrior"),
            Pair("Artist", "en/genres/Artist"),
            Pair("Science Fiction", "en/genres/Science%20Fiction"),
            Pair("Mischief", "en/genres/Mischief"),
            Pair("Actress Collection", "en/genres/Actress%20Collection"),
            Pair("Married Woman", "en/genres/Married%20Woman"),
            Pair("Sweating", "en/genres/Sweating"),
            Pair("Black Male Actor", "en/genres/Black%20Male%20Actor"),
            Pair("Stepmother", "en/genres/Stepmother"),
            Pair("Petite", "en/genres/Petite"),
            Pair("Beautiful Legs", "en/genres/Beautiful%20Legs"),
            Pair("Private Teacher", "en/genres/Private%20Teacher"),
            Pair("Big Pennis", "en/genres/Big%20Pennis"),
            Pair("Super Breasts", "en/genres/Super%20Breasts"),
            Pair("Advertising Idol", "en/genres/Advertising%20Idol"),
            Pair("Torture", "en/genres/Torture"),
            Pair("Emmanuel", "en/genres/Emmanuel"),
            Pair("Anal Sex", "en/genres/Anal%20Sex"),
            Pair("Black Hair", "en/genres/Black%20Hair"),
            Pair("Beautiful Breasts", "en/genres/Beautiful%20Breasts"),
            Pair("Erotic Photo", "en/genres/Erotic%20Photo"),
            Pair("Widow", "en/genres/Widow"),
            Pair("Gym Suit", "en/genres/Gym%20Suit"),
            Pair("Cruel", "en/genres/Cruel"),
            Pair("Sexy", "en/genres/Sexy"),
            Pair("Car Sex", "en/genres/Car%20Sex"),
            Pair("Multiple Stories", "en/genres/Multiple%20Stories"),
            Pair("Campus Story", "en/genres/Campus%20Story"),
            Pair("3P, 4P", "en/genres/3P,%204P"),
            Pair("Transgender", "en/genres/Transgender"),
            Pair("Slim", "en/genres/Slim"),
            Pair("Female Doctor", "en/genres/Female%20Doctor"),
            Pair("In Love", "en/genres/In%20Love"),
            Pair("Fighter", "en/genres/Fighter"),
            Pair("Fantasy", "en/genres/Fantasy"),
            Pair("Pure", "en/genres/Pure"),
            Pair("Virgin", "en/genres/Virgin"),
            Pair("Instant Sex", "en/genres/Instant%20Sex"),
            Pair("Missy", "en/genres/Missy"),
            Pair("Enema", "en/genresenema"),
            Pair("Dance", "en/genres/Dance"),
            Pair("Feminine", "en/genres/Feminine"),
            Pair("Best, Omnibus", "en/genres/Best,%20Omnibus"),
            Pair("Whites", "en/genres/Whites"),
            Pair("Flight Attendant", "en/genres/Flight%20Attendant"),
            Pair("Harem", "en/genres/Harem"),
            Pair("Foreign Actress", "en/genres/Foreign%20Actress"),
            Pair("Physical Education", "en/genres/Physical%20Education"),
            Pair("Bronze", "en/genres/Bronze"),
            Pair("Female Investigator", "en/genres/Female%20Investigator"),
            Pair("Transsexuals", "en/genres/Transsexuals"),
            Pair("Model", "en/genres/Model"),
            Pair("Baby Face", "en/genres/Baby%20Face"),
            Pair("Doggy Style", "en/genres/Doggy%20Style"),
            Pair("Shaving", "en/genres/Shaving"),
            Pair("Bitch", "en/genres/Bitch"),
            Pair("Bloomers", "en/genres/Bloomers"),
            Pair("One Piece Dress", "en/genres/One%20Piece%20Dress"),
            Pair("Knee Socks", "en/genres/Knee%20Socks"),
            Pair("Thanks Offering", "en/genres/Thanks%20Offering"),
            Pair("Cute Little Boy", "en/genres/Cute%20Little%20Boy"),
            Pair("Delivery-Only Amateur", "en/genres/Delivery-Only%20Amateur"),
            Pair("Other", "en/genres/Other"),
            Pair("Bubble Bath", "en/genres/Bubble%20Bath"),
            Pair("Tickle", "en/genres/Tickle"),
            Pair("High School Girl", "en/genres/High%20School%20Girl"),
            Pair("Sister", "en/genres/Sister"),
            Pair("Extreme Orgasm", "en/genres/Extreme%20Orgasm"),
            Pair("Breast Milk", "en/genres/Breast%20Milk"),
            Pair("M Female", "en/genres/M%20Female"),
            Pair("Pregnant Woman", "en/genres/Pregnant%20Woman"),
            Pair("Indie", "en/genres/Indie"),
            Pair("Homosexual", "en/genres/Homosexual"),
            Pair("Vr", "en/genres/Vr"),
            Pair("Drink Urine", "en/genres/Drink%20Urine"),
            Pair("Racing Girl", "en/genres/Racing%20Girl"),
            Pair("Femdom Slave", "en/genres/Femdom%20Slave"),
            Pair("Heaven Tv", "en/genres/Heaven%20Tv"),
            Pair("Secretary", "en/genres/Secretary"),
            Pair("Insult", "en/genres/Insult"),
            Pair("Hot Girl", "en/genres/Hot%20Girl"),
            Pair("Small Breasts", "en/genres/Small%20Breasts"),
            Pair("Rape", "en/genres/Rape"),
            Pair("Thirty", "en/genres/Thirty"),
            Pair("Lolita", "en/genres/Lolita"),
            Pair("Female Boss", "en/genres/Female%20Boss"),
            Pair("Foreign Object Penetration", "en/genres/Foreign%20Object%20Penetration"),
            Pair("Hit On Boys", "en/genres/Hit%20On%20Boys"),
            Pair("Stool", "en/genres/Stool"),
            Pair("Hysteroscope", "en/genres/Hysteroscope"),
            Pair("Young Wife", "en/genres/Young%20Wife"),
            Pair("Defecation", "en/genres/Defecation"),
            Pair("Gang Rape", "en/genres/Gang%20Rape"),
            Pair("Anchorwoman", "en/genres/Anchorwoman"),
            Pair("High Quality Vr", "en/genres/High%20Quality%20Vr"),
            Pair("Similar", "en/genres/Similar"),
            Pair("Transsexuals", "en/genres/Transsexuals"),
            Pair("Catwoman", "en/genres/Catwoman"),
            Pair("Bathtub", "en/genres/Bathtub"),
            Pair("Dildo", "en/genres/Dildo"),
            Pair("Limited Time", "en/genres/Limited%20Time"),
            Pair("Fist", "en/genres/Fist"),
            Pair("Dating", "en/genres/Dating"),
            Pair("Cuckold", "en/genres/Cuckold"),
            Pair("Original", "en/genres/Original"),
            Pair("Lecturer", "en/genres/Lecturer"),
            Pair("Esthetic Massage", "en/genres/Esthetic%20Massage"),
            Pair("Childhood", "en/genres/Childhood"),
            Pair("Uterus", "en/genres/Uterus"),
            Pair("Pregnant", "en/genres/Pregnant"),
            Pair("Entertainer", "en/genresentertainer"),
            Pair("Long Hair", "en/genres/Long%20Hair"),
            Pair("Petite", "en/genres/Petite"),
            Pair("First Shot", "en/genres/First%20Shot"),
            Pair("Muscle", "en/genres/Muscle"),
            Pair("Outdoors", "en/genres/Outdoors"),
            Pair("Naked Apron", "en/genres/Naked%20Apron"),
            Pair("Male Squirting", "en/genres/Male%20Squirting"),
            Pair("Hotel Owner", "en/genres/Hotel%20Owner"),
            Pair("Molester", "en/genres/Molester"),
            Pair("Artist", "en/genres/Artist"),
            Pair("Bunny Girl", "en/genres/Bunny%20Girl"),
            Pair("Travel", "en/genres/Travel"),
            Pair("Racing Girl", "en/genres/Racing%20Girl"),
            Pair("Asian Actress", "en/genres/Asian%20Actress"),
            Pair("Tentacle", "en/genres/Tentacle"),
            Pair("Proud Pussy", "en/genres/Proud%20Pussy"),
            Pair("Subordinate Or Colleague", "en/genres/Subordinate%20Or%20Colleague"),
            Pair("With Bonus Video Only For Mgs", "en/genres/With%20Bonus%20Video%20Only%20For%20Mgs"),
            Pair("Business Clothing", "en/genres/Business%20Clothing"),
            Pair("Premature Ejaculation", "en/genres/Premature%20Ejaculation"),
            Pair("Friend", "en/genres/Friend"),
            Pair("Shame And Humiliation", "en/genres/Shame%20And%20Humiliation"),
            Pair("Big Breasts", "en/genres/Big%20Breasts"),
            Pair("Short Hair", "en/genres/Short%20Hair"),
            Pair("Dildo", "en/genres/Dildo"),
            Pair("Limited Time", "en/genres/Limited%20Time"),
            Pair("Fist", "en/genres/Fist"),
            Pair("Dating", "en/genres/Dating"),
            Pair("Cuckold", "en/genres/Cuckold"),
            Pair("Original", "en/genres/Original"),
            Pair("Lecturer", "en/genres/Lecturer"),
            Pair("Esthetic Massage", "en/genres/Esthetic%20Massage"),
            Pair("Childhood", "en/genres/Childhood"),
            Pair("Uterus", "en/genres/Uterus"),
            Pair("Pregnant", "en/genres/Pregnant"),
            Pair("Entertainer", "en/genresentertainer"),
            Pair("Long Hair", "en/genres/Long%20Hair"),
            Pair("Petite", "en/genres/Petite"),
            Pair("First Shot", "en/genres/First%20Shot"),
            Pair("Muscle", "en/genres/Muscle"),
            Pair("Outdoors", "en/genres/Outdoors"),
            Pair("Naked Apron", "en/genres/Naked%20Apron"),
            Pair("Male Squirting", "en/genres/Male%20Squirting"),
            Pair("Hotel Owner", "en/genres/Hotel%20Owner"),
            Pair("Molester", "en/genres/Molester"),
            Pair("Artist", "en/genres/Artist"),
            Pair("Bunny Girl", "en/genres/Bunny%20Girl"),
            Pair("Travel", "en/genres/Travel"),
            Pair("Racing Girl", "en/genres/Racing%20Girl"),
            Pair("Asian Actress", "en/genres/Asian%20Actress"),
            Pair("Tentacle", "en/genres/Tentacle"),
            Pair("Proud Pussy", "en/genres/Proud%20Pussy"),
            Pair("Subordinate Or Colleague", "en/genres/Subordinate%20Or%20Colleague"),
            Pair("With Bonus Video Only For Mgs", "en/genres/With%20Bonus%20Video%20Only%20For%20Mgs"),
            Pair("Business Clothing", "en/genres/Business%20Clothing"),
            Pair("Premature Ejaculation", "en/genres/Premature%20Ejaculation"),
            Pair("Friend", "en/genres/Friend"),
            Pair("Shame And Humiliation", "en/genres/Shame%20And%20Humiliation"),
            Pair("Big Breasts", "en/genres/Big%20Breasts"),
            Pair("Short Hair", "en/genres/Short%20Hair"),
            Pair("Waitress", "en/genres/Waitress"),
            Pair("Clinic", "en/genres/Clinic"),
            Pair("Exposure", "en/genres/Exposure"),
            Pair("Kimono / Yukata", "en/genres/Kimono%20/%20Yukata"),
            Pair("Lewd Nasty Lady", "en/genres/Lewd%20Nasty%20Lady"),
            Pair("Bubble Socks", "en/genres/Bubble%20Socks"),
            Pair("Fantasy", "en/genres/Fantasy"),
            Pair("Idol", "en/genres/Idol"),
            Pair("Time Stops", "en/genres/Time%20Stops"),
        )
    }
}

// Custom TriState implementation
class TriFilterVal(name: String) : AnimeFilter.TriState(name)

class MultiGenreFilter : AnimeFilter.Group<AnimeFilter.TriState>(
    "Genres (Multi-select)",
    listOf(
        TriFilterVal("Uncensored Leak"),
        TriFilterVal("Hd"),
        TriFilterVal("Exclusive"),
        TriFilterVal("Creampie"),
        TriFilterVal("Big Breasts"),
        TriFilterVal("Individual"),
        TriFilterVal("Wife"),
        TriFilterVal("Mature Woman"),
        TriFilterVal("Ordinary Person"),
        TriFilterVal("Pretty Girl"),
        TriFilterVal("Ride"),
        TriFilterVal("Oral Sex"),
        TriFilterVal("Orgy"),
        TriFilterVal("Slim Pixelated"),
        TriFilterVal("4 Hours Or More"),
        TriFilterVal("Slut"),
        TriFilterVal("Collection"),
        TriFilterVal("High School Girl"),
        TriFilterVal("Squirting"),
        TriFilterVal("Fetish"),
        TriFilterVal("Selfie"),
        TriFilterVal("Tit Job"),
        TriFilterVal("Planning"),
        TriFilterVal("Incest"),
        TriFilterVal("Hit On Girls"),
        TriFilterVal("Sneak Shots"),
        TriFilterVal("Slim"),
        TriFilterVal("Bukkake"),
        TriFilterVal("Beautiful Breasts"),
        TriFilterVal("Masturbate"),
        TriFilterVal("Masturbation"),
        TriFilterVal("Restraint"),
        TriFilterVal("Promiscuous"),
        TriFilterVal("Lesbian"),
        TriFilterVal("Ntr"),
        TriFilterVal("Sister"),
        TriFilterVal("Plot"),
        TriFilterVal("Cosplay"),
        TriFilterVal("Humiliation"),
        TriFilterVal("Documentary"),
        TriFilterVal("Hot Girl"),
        TriFilterVal("Ol"),
        TriFilterVal("Uniform"),
        TriFilterVal("Fingering"),
        TriFilterVal("Vibrator"),
        TriFilterVal("Adultery"),
        TriFilterVal("Cunnilingus"),
        TriFilterVal("Delusion"),
        TriFilterVal("Female College Student"),
        TriFilterVal("Sm"),
        TriFilterVal("Shame"),
        TriFilterVal("Anus"),
        TriFilterVal("Uniform"),
        TriFilterVal("Petite"),
        TriFilterVal("Shaving"),
        TriFilterVal("Subjective Perspective"),
        TriFilterVal("Prostitute"),
        TriFilterVal("Various Occupations"),
        TriFilterVal("Mother"),
        TriFilterVal("Vibrator"),
        TriFilterVal("Toy"),
        TriFilterVal("Promiscuity"),
        TriFilterVal("Outdoor Exposure"),
        TriFilterVal("Butt Fetish"),
        TriFilterVal("Pantyhose"),
        TriFilterVal("Debut"),
        TriFilterVal("Urinate"),
        TriFilterVal("Dirty Talk"),
        TriFilterVal("Massage"),
        TriFilterVal("Underwear"),
        TriFilterVal("Big Ass"),
        TriFilterVal("Forced Blowjob"),
        TriFilterVal("Sailor Suit"),
        TriFilterVal("Swimsuit"),
        TriFilterVal("Delivery Only"),
        TriFilterVal("Female Teacher"),
        TriFilterVal("Kimono"),
        TriFilterVal("Swallow Sperm"),
        TriFilterVal("69"),
        TriFilterVal("Small Breasts"),
        TriFilterVal("Elder Sister"),
        TriFilterVal("Young Wife"),
        TriFilterVal("Nurse"),
        TriFilterVal("Massage Oil"),
        TriFilterVal("Group Bukkake"),
        TriFilterVal("Tied Up"),
        TriFilterVal("Fat Girl"),
        TriFilterVal("Rejuvenation Massage"),
        TriFilterVal("Short Skirt"),
        TriFilterVal("Ultra Slim Pixelated"),
        TriFilterVal("Contribution"),
        TriFilterVal("Nice Ass"),
        TriFilterVal("Foot Fetish"),
        TriFilterVal("Full Hd (Fhd)"),
        TriFilterVal("Glasses Girl"),
        TriFilterVal("Kiss"),
        TriFilterVal("4K"),
        TriFilterVal("Close Up"),
        TriFilterVal("Big Breasts"),
        TriFilterVal("Tied Up"),
        TriFilterVal("Big Breast Fetish"),
        TriFilterVal("Swimsuit"),
        TriFilterVal("Sportswear"),
        TriFilterVal("Virgin"),
        TriFilterVal("Vibrating Egg"),
        TriFilterVal("Aphrodisiac"),
        TriFilterVal("Lesbian Kiss"),
        TriFilterVal("Mini Skirt"),
        TriFilterVal("White Skin"),
        TriFilterVal("M Male"),
        TriFilterVal("Couple"),
        TriFilterVal("Hot Spring"),
        TriFilterVal("Maid"),
        TriFilterVal("Face Ride"),
        TriFilterVal("Imprisonment"),
        TriFilterVal("Footjob"),
        TriFilterVal("Fighting"),
        TriFilterVal("Tall Lady"),
        TriFilterVal("Female Warrior"),
        TriFilterVal("Artist"),
        TriFilterVal("Science Fiction"),
        TriFilterVal("Mischief"),
        TriFilterVal("Actress Collection"),
        TriFilterVal("Married Woman"),
        TriFilterVal("Sweating"),
        TriFilterVal("Black Male Actor"),
        TriFilterVal("Stepmother"),
        TriFilterVal("Petite"),
        TriFilterVal("Beautiful Legs"),
        TriFilterVal("Private Teacher"),
        TriFilterVal("Big Pennis"),
        TriFilterVal("Super Breasts"),
        TriFilterVal("Advertising Idol"),
        TriFilterVal("Torture"),
        TriFilterVal("Emmanuel"),
        TriFilterVal("Anal Sex"),
        TriFilterVal("Black Hair"),
        TriFilterVal("Beautiful Breasts"),
        TriFilterVal("Erotic Photo"),
        TriFilterVal("Widow"),
        TriFilterVal("Gym Suit"),
        TriFilterVal("Cruel"),
        TriFilterVal("Sexy"),
        TriFilterVal("Car Sex"),
        TriFilterVal("Multiple Stories"),
        TriFilterVal("Campus Story"),
        TriFilterVal("3P, 4P"),
        TriFilterVal("Transgender"),
        TriFilterVal("Slim"),
        TriFilterVal("Female Doctor"),
        TriFilterVal("In Love"),
        TriFilterVal("Fighter"),
        TriFilterVal("Fantasy"),
        TriFilterVal("Pure"),
        TriFilterVal("Virgin"),
        TriFilterVal("Instant Sex"),
        TriFilterVal("Missy"),
        TriFilterVal("Enema"),
        TriFilterVal("Dance"),
        TriFilterVal("Feminine"),
        TriFilterVal("Best, Omnibus"),
        TriFilterVal("Whites"),
        TriFilterVal("Flight Attendant"),
        TriFilterVal("Harem"),
        TriFilterVal("Foreign Actress"),
        TriFilterVal("Physical Education"),
        TriFilterVal("Bronze"),
        TriFilterVal("Female Investigator"),
        TriFilterVal("Transsexuals"),
        TriFilterVal("Model"),
        TriFilterVal("Baby Face"),
        TriFilterVal("Doggy Style"),
        TriFilterVal("Shaving"),
        TriFilterVal("Bitch"),
        TriFilterVal("Bloomers"),
        TriFilterVal("One Piece Dress"),
        TriFilterVal("Knee Socks"),
        TriFilterVal("Thanks Offering"),
        TriFilterVal("Cute Little Boy"),
        TriFilterVal("Delivery-Only Amateur"),
        TriFilterVal("Other"),
        TriFilterVal("Bubble Bath"),
        TriFilterVal("Tickle"),
        TriFilterVal("High School Girl"),
        TriFilterVal("Sister"),
        TriFilterVal("Extreme Orgasm"),
        TriFilterVal("Breast Milk"),
        TriFilterVal("M Female"),
        TriFilterVal("Pregnant Woman"),
        TriFilterVal("Indie"),
        TriFilterVal("Homosexual"),
        TriFilterVal("Vr"),
        TriFilterVal("Drink Urine"),
        TriFilterVal("Racing Girl"),
        TriFilterVal("Femdom Slave"),
        TriFilterVal("Heaven Tv"),
        TriFilterVal("Secretary"),
        TriFilterVal("Insult"),
        TriFilterVal("Hot Girl"),
        TriFilterVal("Small Breasts"),
        TriFilterVal("Rape"),
        TriFilterVal("Thirty"),
        TriFilterVal("Lolita"),
        TriFilterVal("Female Boss"),
        TriFilterVal("Foreign Object Penetration"),
        TriFilterVal("Hit On Boys"),
        TriFilterVal("Stool"),
        TriFilterVal("Hysteroscope"),
        TriFilterVal("Young Wife"),
        TriFilterVal("Defecation"),
        TriFilterVal("Gang Rape"),
        TriFilterVal("Anchorwoman"),
        TriFilterVal("High Quality Vr"),
        TriFilterVal("Similar"),
        TriFilterVal("Transsexuals"),
        TriFilterVal("Catwoman"),
        TriFilterVal("Bathtub"),
        TriFilterVal("Dildo"),
        TriFilterVal("Limited Time"),
        TriFilterVal("Fist"),
        TriFilterVal("Dating"),
        TriFilterVal("Cuckold"),
        TriFilterVal("Original"),
        TriFilterVal("Lecturer"),
        TriFilterVal("Esthetic Massage"),
        TriFilterVal("Childhood"),
        TriFilterVal("Uterus"),
        TriFilterVal("Pregnant"),
        TriFilterVal("Entertainer"),
        TriFilterVal("Long Hair"),
        TriFilterVal("Petite"),
        TriFilterVal("First Shot"),
        TriFilterVal("Muscle"),
        TriFilterVal("Outdoors"),
        TriFilterVal("Naked Apron"),
        TriFilterVal("Male Squirting"),
        TriFilterVal("Hotel Owner"),
        TriFilterVal("Molester"),
        TriFilterVal("Artist"),
        TriFilterVal("Bunny Girl"),
        TriFilterVal("Travel"),
        TriFilterVal("Racing Girl"),
        TriFilterVal("Asian Actress"),
        TriFilterVal("Tentacle"),
        TriFilterVal("Proud Pussy"),
        TriFilterVal("Subordinate Or Colleague"),
        TriFilterVal("With Bonus Video Only For Mgs"),
        TriFilterVal("Business Clothing"),
        TriFilterVal("Premature Ejaculation"),
        TriFilterVal("Friend"),
        TriFilterVal("Shame And Humiliation"),
        TriFilterVal("Big Breasts"),
        TriFilterVal("Short Hair"),
        TriFilterVal("Dildo"),
        TriFilterVal("Limited Time"),
        TriFilterVal("Fist"),
        TriFilterVal("Dating"),
        TriFilterVal("Cuckold"),
        TriFilterVal("Original"),
        TriFilterVal("Lecturer"),
        TriFilterVal("Esthetic Massage"),
        TriFilterVal("Childhood"),
        TriFilterVal("Uterus"),
        TriFilterVal("Pregnant"),
        TriFilterVal("Entertainer"),
        TriFilterVal("Long Hair"),
        TriFilterVal("Petite"),
        TriFilterVal("First Shot"),
        TriFilterVal("Muscle"),
        TriFilterVal("Outdoors"),
        TriFilterVal("Naked Apron"),
        TriFilterVal("Male Squirting"),
        TriFilterVal("Hotel Owner"),
        TriFilterVal("Molester"),
        TriFilterVal("Artist"),
        TriFilterVal("Bunny Girl"),
        TriFilterVal("Travel"),
        TriFilterVal("Racing Girl"),
        TriFilterVal("Asian Actress"),
        TriFilterVal("Tentacle"),
        TriFilterVal("Proud Pussy"),
        TriFilterVal("Subordinate Or Colleague"),
        TriFilterVal("With Bonus Video Only For Mgs"),
        TriFilterVal("Business Clothing"),
        TriFilterVal("Premature Ejaculation"),
        TriFilterVal("Friend"),
        TriFilterVal("Shame And Humiliation"),
        TriFilterVal("Big Breasts"),
        TriFilterVal("Short Hair"),
        TriFilterVal("Waitress"),
        TriFilterVal("Clinic"),
        TriFilterVal("Exposure"),
        TriFilterVal("Kimono / Yukata"),
        TriFilterVal("Lewd Nasty Lady"),
        TriFilterVal("Bubble Socks"),
        TriFilterVal("Fantasy"),
        TriFilterVal("Idol"),
        TriFilterVal("Time Stops"),
    ),
)

fun getFilters() = AnimeFilterList(
    SortFilter(),
    GenreList(),
    MultiGenreFilter(),
    AnimeFilter.Separator(),
    AnimeFilter.Header("Multi-genre filtering is client-side and may be slow"),
    AnimeFilter.Header("Green ✓ = Include | Red ✗ = Exclude | Empty = Ignore"),
)

data class FilterSearchParams(
    val genres: List<String> = emptyList(),
    val blacklisted: List<String> = emptyList(),
)

internal fun getSearchParameters(filters: AnimeFilterList): FilterSearchParams {
    if (filters.isEmpty()) return FilterSearchParams()

    val multiGenreFilter = filters.getOrNull(2) as? MultiGenreFilter

    if (multiGenreFilter != null) {
        val included = mutableListOf<String>()
        val excluded = mutableListOf<String>()

        multiGenreFilter.state.forEach { triState ->
            val genreName = triState.name
            when (triState.state) {
                AnimeFilter.TriState.STATE_INCLUDE -> included.add(genreName)
                AnimeFilter.TriState.STATE_EXCLUDE -> excluded.add(genreName)
                else -> {}
            }
        }

        return FilterSearchParams(included, excluded)
    }

    return FilterSearchParams()
}
