name: Fork CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '!**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  CI_CHUNK_SIZE: 288

jobs:
  prepare:
    name: Prepare job
    runs-on: ubuntu-latest
    outputs:
      individualMatrix: ${{ steps.generate-matrices.outputs.individualMatrix }}
    steps:
    - name: Clone repo
      uses: actions/checkout@v4

    - name: Get number of modules  
      run: |  
        projects=(src/*/*)  
        echo "NUM_INDIVIDUAL_MODULES=${#projects[@]}" >> "$GITHUB_ENV"  

    - name: Find lib changes  
      id: modified-libs  
      uses: tj-actions/changed-files@v46  
      with:  
        files: lib/  
        files_ignore: lib/**.md  
        files_separator: " "  
        safe_output: false  

    - name: Skip lib bumping in forks
      if: github.repository != 'Kohi-den/extensions-source'
      run: echo "Skipping lib bumping in fork"

    - id: generate-matrices  
      name: Create output matrices  
      uses: actions/github-script@v7  
      with:  
        script: |  
          const numIndividualModules = process.env.NUM_INDIVIDUAL_MODULES;  
          const chunkSize = process.env.CI_CHUNK_SIZE;  
          const numIndividualChunks = 1;  
          console.log(`Individual modules: ${numIndividualModules} (${numIndividualChunks} chunks of ${chunkSize})`);  
          core.setOutput('individualMatrix', { 'chunk': [...Array(numIndividualChunks).keys()] });

  build_individual:
    name: Build individual modules
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.individualMatrix) }}
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4

    - name: Set up JDK  
      uses: actions/setup-java@v4  
      with:  
        java-version: 17  
        distribution: temurin  
          
    - name: Set up Android SDK  
      uses: android-actions/setup-android@v3  
        
    - name: Set up Gradle  
      uses: gradle/actions/setup-gradle@v4  

    - name: Build debug APKs  
      run: chmod +x ./gradlew && ./gradlew -p src assembleDebug  

    - name: Upload APKs  
      uses: actions/upload-artifact@v4
      with:  
        name: "individual-apks-${{ matrix.chunk }}"  
        path: "**/*.apk"  
        retention-days: 1
