name: Build hanime1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew

      - name: Patch settings.gradle.kts to include only hanime1
        run: |
          echo """
          rootProject.name = "extensions"

          include(":src:zh:hanime1")
          project(":src:zh:hanime1").projectDir = file("src/zh/hanime1")
          """ > settings.gradle.kts

      - name: Build hanime1
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hanime1-apk
          path: src/zh/hanime1/build/outputs/apk/release/*.apk
