name: Build APKs

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  CI_CHUNK_SIZE: 65

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Count modules and generate matrix
        id: set-matrix
        run: |
          projects=(src/*/*)
          total=${#projects[@]}
          chunk_size=${{ env.CI_CHUNK_SIZE }}
          chunks=$(( (total + chunk_size - 1) / chunk_size ))

          matrix_json=$(jq -n --argjson chunks "$chunks" '{chunk: [range(0; $chunks)]}')
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build APKs (chunk ${{ matrix.chunk }})
        env:
          CI_CHUNK_NUM: ${{ matrix.chunk }}
        run: |
          chmod +x ./gradlew
          ./gradlew -p src assembleRelease

      - name: Upload APKs (chunk ${{ matrix.chunk }})
        uses: actions/upload-artifact@v4
        with:
          name: apks-chunk-${{ matrix.chunk }}
          path: '**/*.apk'
