name: Build hanime1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew

      - name: Build hanime1
        env:
          CI_CHUNK_SIZE: 1     # Prevent getenv() null error
          CI_CHUNK_NUM: 0      # Any value, not used for single module
        run: ./gradlew -p src/zh/hanime1 assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hanime1-apk
          path: src/zh/hanime1/build/outputs/apk/release/*.apk
