name: Build Single Extension

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Package APK
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build specific extension
        env:
          # Fix for Kotlin serialization warnings
          GRADLE_OPTS: -Dorg.gradle.parallel=false -Dkotlinx.serialization.opt-in=kotlinx.serialization.ExperimentalSerializationApi
        run: |
          chmod +x ./gradlew
          # Build only the hanime1 extension
          ./gradlew :src:zh:hanime1:assembleDebug

      - name: Collect APK
        run: |
          # Create output directory
          mkdir apk_output
          # Find and copy the specific APK
          find src/zh/hanime1 -name '*.apk' -exec cp -v {} apk_output \;
          echo "APK collected: $(ls apk_output/)"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: hanime1-extension
          path: apk_output/*.apk
          retention-days: 1
