name: Build Single APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Package APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build specific module
        env:
          GRADLE_OPTS: -Dorg.gradle.parallel=false
        run: |
          chmod +x ./gradlew
          ./gradlew :zh:hanime1:assembleDebug

      - name: Find and archive APK
        run: |
          mkdir apk_output
          find . -path "*/zh/hanime1/*/debug/*.apk" -exec cp -v {} apk_output \;
          echo "APK found at: $(ls apk_output/)"
          zip -j single_apk.zip apk_output/*.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: hanime1-extension
          path: single_apk.zip
          retention-days: 1
