name: Build Hanime1 Extension

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: -Dorg.gradle.parallel=false -Dkotlinx.serialization.opt-in=kotlinx.serialization.ExperimentalSerializationApi

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: extensions-source

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Verify directory structure
        run: |
          echo "Working directory: $(pwd)"
          cd extensions-source
          echo "Project directory: $(pwd)"
          ls -la
          ls -la src/zh/

      - name: Build hanime1 extension
        run: |
          cd extensions-source
          chmod +x ./gradlew
          ./gradlew :src:zh:hanime1:assembleDebug

      - name: Find and upload APK
        run: |
          cd extensions-source
          APK_PATH=$(find src/zh/hanime1/build/outputs/apk/debug -name '*.apk')
          if [ -z "$APK_PATH" ]; then
            echo "APK not found! Searching all locations:"
            find . -name "*.apk"
            exit 1
          fi
          echo "APK found at: $APK_PATH"
          cp "$APK_PATH" ../hanime1-debug.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: hanime1-extension
          path: hanime1-debug.apk
          retention-days: 1
